const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={books:[],texts:new Map()};
async function json(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error(`${path} ${r.status}`);return r.json()}
async function text(book){if(state.texts.has(book.id))return state.texts.get(book.id);const r=await fetch(book.path,{cache:'no-store'});if(!r.ok)throw Error(`${book.path} ${r.status}`);const t=await r.text();state.texts.set(book.id,t);return t}
function library(){const list=document.querySelector('#book-list');list.innerHTML=state.books.map(b=>`<article class="book-card"><div><span class="book-tag">${esc(b.tradition)}</span><h3>${esc(b.title)}</h3><p>${esc(b.author)}${b.translator?` · ${esc(b.translator)}`:''} · ${esc(b.publication_year)}</p><p class="muted">Complete reusable text stored locally: ${Number(b.repository_size_bytes||0).toLocaleString()} bytes.</p></div><div class="book-actions"><a class="primary" href="${esc(b.reader)}?book=${encodeURIComponent(b.id)}">Read & search</a><a href="${esc(b.path)}" target="_blank" rel="noopener">Open raw text</a><a href="${esc(b.source_url)}" target="_blank" rel="noopener">Edition source</a></div></article>`).join('');const filter=document.querySelector('#book-filter');filter.innerHTML='<option value="all">All registered books</option>'+state.books.map(b=>`<option value="${esc(b.id)}">${esc(b.short_title||b.title)}</option>`).join('')}
function snippet(t,i,q,span){const a=Math.max(0,i-span),z=Math.min(t.length,i+q.length+span);return `${a?'…':''}${t.slice(a,z).replace(/\s+/g,' ').trim()}${z<t.length?'…':''}`}
function mark(s,q){const e=esc(q).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return esc(s).replace(new RegExp(e,'gi',),m=>`<mark>${m}</mark>`) }
async function search(){const q=document.querySelector('#book-query').value.trim();const section=document.querySelector('#book-results-section');if(!q){section.hidden=true;return}const selected=document.querySelector('#book-filter').value;const span=Number(document.querySelector('#book-context').value);const books=state.books.filter(b=>selected==='all'||b.id===selected);const out=document.querySelector('#book-results');out.innerHTML='';document.querySelector('#book-status').textContent='Reading the stored full texts…';let total=0;for(const b of books){try{const t=await text(b);const low=t.toLocaleLowerCase();const needle=q.toLocaleLowerCase();let p=0,guard=0;while(guard++<1000){const i=low.indexOf(needle,p);if(i<0)break;total++;const line=t.slice(0,i).split('\n').length;const s=snippet(t,i,q,span);out.insertAdjacentHTML('beforeend',`<article class="result"><div class="result-head"><span class="book-tag">${esc(b.short_title||b.title)}</span><span class="muted">line ${line}</span></div><p>${mark(s,q)}</p><div class="result-links"><a href="${esc(b.reader)}?book=${encodeURIComponent(b.id)}&q=${encodeURIComponent(q)}&line=${line}">Open in reader</a><a href="${esc(b.path)}" target="_blank" rel="noopener">Open complete text</a></div></article>`);p=i+Math.max(1,q.length);if(total>=300)break}}catch(e){out.insertAdjacentHTML('beforeend',`<article class="result"><h3>${esc(b.title)}</h3><p class="error">${esc(e.message)}</p></article>`)}}section.hidden=false;document.querySelector('#result-count').textContent=`${total} passage${total===1?'':'s'} found`;document.querySelector('#book-status').textContent=`${books.length} full text${books.length===1?'':'s'} searched locally.`}
document.querySelector('#book-search').addEventListener('click',search);document.querySelector('#book-query').addEventListener('keydown',e=>{if(e.key==='Enter')search()});document.querySelector('#book-filter').addEventListener('change',()=>{if(document.querySelector('#book-query').value.trim())search()});
(async()=>{try{const r=await json('data/books-registry.json');state.books=r.books||[];library();document.querySelector('#book-status').textContent=`${state.books.length} complete text editions registered.`}catch(e){document.querySelector('#book-status').textContent=e.message}})();
