const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const registryUrl='data/books-registry.json';
const state={books:[],texts:new Map(),loaded:new Set()};
async function getJson(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error(`${path} ${r.status}`);return r.json()}
async function getText(book){if(state.texts.has(book.id))return state.texts.get(book.id);const r=await fetch(book.path,{cache:'no-store'});if(!r.ok)throw Error(`${book.path} ${r.status}`);const t=await r.text();state.texts.set(book.id,t);state.loaded.add(book.id);return t}
function renderLibrary(){const list=document.getElementById('book-list');const filter=document.getElementById('book-filter');list.innerHTML=state.books.map(b=>`<article class="book-card"><div><span class="book-tag">${esc(b.tradition)}</span><h3>${esc(b.title)}</h3><p>${esc(b.author)}${b.translator?' · translated by '+esc(b.translator):''}</p><p class="muted">${esc(b.notes||'')}</p></div><div class="book-actions"><button type="button" data-load="${esc(b.id)}">Load text</button><a href="${esc(b.path)}" target="_blank" rel="noopener">Open raw TXT</a><a href="${esc(b.source_url)}" target="_blank" rel="noopener">Source</a></div></article>`).join('');
for(const b of state.books){const o=document.createElement('option');o.value=b.id;o.textContent=b.short_title||b.title;filter.appendChild(o)}
list.querySelectorAll('[data-load]').forEach(btn=>btn.addEventListener('click',async()=>{const b=state.books.find(x=>x.id===btn.dataset.load);if(!b)return;btn.disabled=true;btn.textContent='Loading…';try{await getText(b);btn.textContent='Loaded';document.getElementById('book-status').textContent=`${state.loaded.size} text${state.loaded.size===1?'':'s'} loaded into the browser.`}catch(e){btn.disabled=false;btn.textContent='Load text';document.getElementById('book-status').textContent=e.message}}))}
function contextSnippet(text,index,span){const start=Math.max(0,index-span),end=Math.min(text.length,index+span);let s=text.slice(start,end).replace(/\s+/g,' ').trim();if(start>0)s='…'+s;if(end<text.length)s+='…';return s}
function highlight(text,q){const escaped=q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return esc(text).replace(new RegExp(escaped,'gi'),m=>`<mark>${esc(m)}</mark>`) }
async function search(){const q=document.getElementById('book-query').value.trim();const section=document.getElementById('book-results-section');const out=document.getElementById('book-results');if(!q){section.hidden=true;return}const filter=document.getElementById('book-filter').value;const span=Number(document.getElementById('book-context').value);const books=state.books.filter(b=>filter==='all'||b.id===filter);document.getElementById('book-status').textContent='Loading selected full texts…';const results=[];for(const b of books){try{const text=await getText(b);let from=0,guard=0;while(guard++<500){const i=text.toLocaleLowerCase().indexOf(q.toLocaleLowerCase(),from);if(i<0)break;results.push({book:b,index:i,snippet:contextSnippet(text,i,span)});from=i+Math.max(q.length,1);if(results.length>=200)break}}catch(e){results.push({book:b,error:e.message})}}
results.sort((a,b)=>a.index-b.index);section.hidden=false;document.getElementById('result-count').textContent=`${results.length} match${results.length===1?'':'es'}`;out.innerHTML=results.length?results.map((r,n)=>r.error?`<article class="result"><h3>${esc(r.book.short_title||r.book.title)}</h3><p class="error">Could not load text: ${esc(r.error)}</p></article>`:`<article class="result"><div class="result-head"><span class="book-tag">${esc(r.book.short_title||r.book.title)}</span><span class="muted">match ${n+1}</span></div><p>${highlight(r.snippet,q)}</p><a href="${esc(r.book.path)}#${Math.max(0,r.index)}" target="_blank" rel="noopener">Open raw text</a></article>`).join(''):'<div class="empty">No matches in the selected full texts.</div>';document.getElementById('book-status').textContent=`${state.loaded.size} text${state.loaded.size===1?'':'s'} loaded.`}
document.getElementById('book-search').addEventListener('click',search);document.getElementById('book-query').addEventListener('keydown',e=>{if(e.key==='Enter')search()});document.getElementById('book-filter').addEventListener('change',()=>{if(document.getElementById('book-query').value.trim())search()});
(async()=>{try{const r=await getJson(registryUrl);state.books=r.books||[];renderLibrary();document.getElementById('book-status').textContent=`${state.books.length} full-text editions registered.`}catch(e){document.getElementById('book-status').textContent=e.message}})();
