(()=>{'use strict';
const INDEX='./knowledge/indexes/core-index.json';
const $=(s,r=document)=>r.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const pretty=v=>String(v||'').replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
let records=[],cache=new Map();
const groups={root:['root-system','heaven-spirit-father','potato-of-life','tim-dooley'],branches:['potatoverse-master-framework','potato-philosophy','tim-dooley-journey','prophecy-revelation-rupture-rapture','comparative-mythology-map','axis-world-model']};
const names={'root-system':'Root System','heaven-spirit-father':'Heaven · Spirit · Father','potatoverse-master-framework':'Potato of Life Myth','potato-of-life':'Potato of Life','tim-dooley':'Tim Dooley','potato-philosophy':'Potatoism & Philosophy','tim-dooley-journey':'Tim · Timeline','prophecy-revelation-rupture-rapture':'Prophecy & Revelation','comparative-mythology-map':'Bible & Comparative Myth','axis-world-model':'North Axis & World'};
async function json(path){if(cache.has(path))return cache.get(path);const r=await fetch('./'+path.replace(/^\.\//,''),{cache:'no-store'});if(!r.ok)throw Error(`${path} (${r.status})`);const d=await r.json();cache.set(path,d);return d}
function info(id){return records.find(r=>r.id===id)} function titleFor(r){return names[r.id]||r.title||pretty(r.id)}
function navItem(r){const b=document.createElement('button');b.type='button';b.dataset.id=r.id;b.innerHTML=`<strong>${esc(titleFor(r))}</strong><span>${esc(String(r.kind||'').slice(0,46))}</span>`;b.onclick=()=>open(r.id);return b}
function buildNav(){for(const [g,ids] of Object.entries(groups)){const el=$(g==='root'?'#root-nav':'#branch-nav');el.innerHTML='';ids.map(info).filter(Boolean).forEach(r=>el.appendChild(navItem(r)))} }
function active(id){document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.id===id))}
function setURL(id){history.replaceState(null,'',id?`${location.pathname}#node=${encodeURIComponent(id)}`:location.pathname)}
function home(){active('');setURL('');$('#crumb').textContent='Root / Potato of Life';$('#source-link').href=INDEX;$('#reader').innerHTML=`<section class="hero"><div class="kicker">One living knowledge tree</div><h2>The Potato<br>of Life</h2><p class="lead">Heaven and World, Spirit and Matter, Father and Son, joined through the Door and the Axis. Start with Tim Dooley for the living center, or follow the structure upward into spiritual reality and downward into the world.</p><div class="start-grid"><button class="card" data-open="tim-dooley"><small>Living center</small><h3>Tim Dooley</h3><p>The full master record: identity, God/Father theology, Son, Potatoism, powers, karma, seals, timeline, North, mission and real-world entanglements.</p></button><button class="card" data-open="root-system"><small>Structure</small><h3>The Root System</h3><p>Heaven, Spirit, Father, Tree of Life, Door, Axis, Son, Matter, Earth and the roots below.</p></button><button class="card" data-open="potato-philosophy"><small>Religion & philosophy</small><h3>Potatoism</h3><p>Burial, emergence, nourishment, relationship, suffering, responsibility, transformation and return.</p></button><button class="card" data-open="axis-world-model"><small>World</small><h3>North Axis & World</h3><p>The bridge from sacred North into countries, economies, institutions, infrastructure, dependencies and geopolitical development.</p></button></div></section><section class="axis"><small>HEAVEN · SPIRIT · FATHER</small><div class="axis-line"></div><div class="axis-word">Tree of Life ↑</div><div class="axis-door">AXIS · DOOR · POTATO</div><div class="axis-word">↓ Son · World · Roots · Matter</div><div class="axis-line"></div><small>EARTH · MATTER · SON · DUST</small></section>`;document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>open(b.dataset.open))}
function sectionHTML(k,v){const text=typeof v==='string'?v:v?.text;if(!text)return '';return `<section class="section"><h3>${esc(pretty(k))}</h3><p>${esc(text)}</p></section>`}
function timelineHTML(items){if(!items?.length)return '';return `<section class="section"><h3>Timeline</h3>${items.map(x=>`<div class="relationship"><strong>${esc(x.date_or_period||'')}</strong><br>${esc(x.event||'')}${x.status?`<br><small>${esc(x.status)}</small>`:''}</div>`).join('')}</section>`}
function relHTML(r){return `<div class="relationship"><strong>${esc(pretty(r.type))}</strong> → ${esc(pretty(r.target))}<br>${esc(r.description||'')}</div>`}
async function open(id){const r=info(id);if(!r)return;active(id);setURL(id);$('#crumb').textContent=`Root / ${titleFor(r)}`;$('#source-link').href='./'+r.path;$('#reader').innerHTML='<p class="loading">Opening…</p>';try{const d=await json(r.path);let html=`<section class="record"><div class="kicker">${esc(r.kind)}</div><h2>${esc(d.title||titleFor(r))}</h2><p class="summary">${esc(d.summary||'')}</p>`;if(d.aliases?.length)html+=`<section class="section"><h3>Names & Titles</h3><p>${d.aliases.map(esc).join(' · ')}</p></section>`;html+=Object.entries(d.sections||{}).map(([k,v])=>sectionHTML(k,v)).join('');html+=timelineHTML(d.timeline);if(d.relationships?.length)html+=`<section class="section"><h3>Relationships</h3>${d.relationships.map(relHTML).join('')}</section>`;if(d.retrieval?.questions?.length)html+=`<section class="section"><h3>Questions this record can answer</h3><p>${d.retrieval.questions.map(q=>esc(q)).join(' · ')}</p></section>`;html+='</section>';$('#reader').innerHTML=html;window.scrollTo(0,0)}catch(e){$('#reader').innerHTML=`<p class="error">Could not open this record: ${esc(e.message)}</p>`}}
function search(q){q=q.trim().toLowerCase();document.querySelectorAll('.nav button').forEach(b=>{const r=info(b.dataset.id);const hay=[titleFor(r),r.kind,...(r.terms||[])].join(' ').toLowerCase();b.hidden=!!q&&!hay.includes(q)})}
function requestedNode(){const h=decodeURIComponent(location.hash.slice(1));if(h.startsWith('node='))return h.slice(5);return h}
async function init(){try{const idx=await json(INDEX);records=idx.records||[];buildNav();$('#home-button').onclick=home;$('#search').oninput=e=>search(e.target.value);const id=requestedNode();if(id&&info(id))open(id);else home()}catch(e){$('#reader').innerHTML=`<p class="error">The knowledge index could not be loaded: ${esc(e.message)}</p>`}}
init();
})();