(() => {
  'use strict';
  const DATA_URL='data/root-record-index.json', MANIFEST_URL='data/root-navigation.json', STORAGE_KEY='potato-root-state-v4';
  const $=(s,r=document)=>r.querySelector(s), esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const state={manifest:null,records:[],selected:null,expanded:new Set(),rendered:new Set()};
  const save=()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify({expanded:[...state.expanded],selected:state.selected}));}catch(_){}};
  const load=()=>{try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');(x.expanded||[]).forEach(k=>state.expanded.add(k));state.selected=x.selected||null;}catch(_){}};
  const hash=id=>history.replaceState(null,'',id?`${location.pathname}#node=${encodeURIComponent(id)}`:location.pathname);
  const hashId=()=>new URLSearchParams(location.hash.replace(/^#/,'')).get('node');
  const unique=rows=>{const seen=new Set();return rows.filter(r=>{const k=r.canonical_id||`${r.source}:${r.id}:${JSON.stringify(r.path||[])}`;if(seen.has(k))return false;seen.add(k);return true;}).sort((a,b)=>String(a.name||a.id).localeCompare(String(b.name||b.id)));};
  function matches(r,c){if(c.all)return true;if(c.paths?.length)return c.paths.some(p=>(r.navigation_path||[]).join('/').toLowerCase()===String(p).toLowerCase());if(c.root&&String(r.repository_root).toLowerCase()!==String(c.root).toLowerCase())return false;if(c.types?.length&&!c.types.includes(String(r.type||'').toLowerCase()))return false;if(c.families?.length&&!c.families.includes(String(r.owner_family||'').toLowerCase()))return false;if(c.scales?.length&&!c.scales.includes(String(r.repository_scale||'').toLowerCase()))return false;if(c.role&&String(r.record_role||'').toLowerCase()!==String(c.role).toLowerCase())return false;if(c.terms?.length){const h=[r.id,r.name,r.description,r.source,r.owner_family,r.repository_layer,(r.navigation_path||[]).join(' ')].join(' ').toLowerCase();if(!c.terms.some(t=>h.includes(String(t).toLowerCase())))return false;}return !!(c.types||c.families||c.scales||c.role||c.terms);}
  function select(r,path){state.selected=r.canonical_id||r.id;hash(state.selected);showDossier(r,path);save();}
  function showDossier(r,path){const d=$('#root-dossier');if(!d)return;d.hidden=false;d.innerHTML=`<div class="dossier-head"><div><div class="eyebrow">${esc(path||'record')}</div><h2>${esc(r.name||r.id)}</h2></div><button class="dossier-close" data-action="close-dossier" aria-label="Close">×</button></div><p class="dossier-description">${esc(r.description||'No description is currently registered for this record.')}</p><dl class="dossier-meta"><div><dt>ID</dt><dd>${esc(r.canonical_id||r.id||'')}</dd></div><div><dt>TYPE</dt><dd>${esc(r.type||'record')}</dd></div><div><dt>ROLE</dt><dd>${esc(r.record_role||'')}</dd></div><div><dt>FAMILY</dt><dd>${esc(r.owner_family||'')}</dd></div><div><dt>CLASS</dt><dd>${esc(r.repository_root||'')} / ${esc(r.repository_layer||'')} / ${esc(r.repository_scale||'')}</dd></div><div><dt>SOURCE</dt><dd>${esc(r.source||'generated registry')}</dd></div></dl></div>`;d.scrollIntoView({behavior:'smooth',block:'nearest'});}
  function showCenterRecord(r){const d=$('#root-dossier');if(!d)return;d.hidden=false;d.innerHTML=`<div class="dossier-head"><div><div class="eyebrow">CENTER / ${esc(r.id)}</div><h2>${esc(r.label)}</h2></div><button class="dossier-close" data-action="close-dossier" aria-label="Close">×</button></div><p class="dossier-description">${esc(state.manifest.center.description)} This is an in-place center entry; the interface does not leave the index to open a separate page.</p>`;state.selected=r.id;hash(r.id);save();d.scrollIntoView({behavior:'smooth',block:'nearest'});}
  function close(){state.selected=null;$('#root-dossier').hidden=true;hash(null);save();}
  function recordRow(r,path){const x=document.createElement('div');x.className='tree-entry record-entry';x.innerHTML=`<span class="tree-mark">├─</span><button class="tree-button" type="button">${esc(r.name||r.id)}</button><span class="tree-note">${esc(r.description||r.type||r.id||'')}</span>`;$('.tree-button',x).onclick=()=>select(r,path);return x;}
  function renderCollection(details,c,branch){const key=`collection:${branch}:${c.id}`;if(state.rendered.has(key))return;state.rendered.add(key);const box=$('.tree-children',details),rows=unique(state.records.filter(r=>matches(r,c)));box.innerHTML='';const groups=new Map();rows.forEach(r=>{const g=(r.navigation_path||[branch,c.id,'RECORDS']).slice(-1)[0]||'RECORDS';if(!groups.has(g))groups.set(g,[]);groups.get(g).push(r);});if(rows.length>120){for(const [g,rs] of [...groups.entries()].sort()){const sub=document.createElement('details');sub.className='tree-subdir';sub.innerHTML=`<summary><span class="tree-mark">│</span><span class="tree-name">${esc(g)}/</span><span class="tree-note">${rs.length} records</span></summary><div class="tree-children"></div>`;rs.forEach(r=>$('.tree-children',sub).appendChild(recordRow(r,`${branch}/${c.id}/${g}`)));box.appendChild(sub);}}else rows.forEach(r=>box.appendChild(recordRow(r,`${branch}/${c.id}`)));if(!box.children.length)box.innerHTML='<div class="tree-empty">no indexed records in this view</div>';}
  function collection(c,branch){const d=document.createElement('details');d.className='tree-dir tree-collection';const key=`collection:${branch}:${c.id}`;d.innerHTML=`<summary><span class="tree-mark">│</span><span class="tree-name">${esc(c.label)}</span><span class="tree-note">${esc(c.description||'')}</span><span class="tree-count">…</span></summary><div class="tree-children"></div>`;d.addEventListener('toggle',()=>{if(d.open){state.expanded.add(key);renderCollection(d,c,branch);}else state.expanded.delete(key);save();});if(state.expanded.has(key)){d.open=true;renderCollection(d,c,branch);}return d;}
  function branch(b,cs){const d=document.createElement('details');d.className=`tree-dir tree-branch branch-${b.kind}`;const key=`branch:${b.id}`;d.innerHTML=`<summary><span class="tree-mark">│</span><span class="tree-name">${esc(b.label)}</span><span class="tree-note">${esc(b.description)}</span><span class="tree-count">${cs.length}</span></summary><div class="tree-children branch-children"></div>`;cs.forEach(c=>$('.branch-children',d).appendChild(collection(c,b.id)));d.addEventListener('toggle',()=>{if(d.open)state.expanded.add(key);else state.expanded.delete(key);save();});if(state.expanded.has(key))d.open=true;return d;}
  function center(){const c=$('#root-center'),rs=state.manifest.center.records||[];c.innerHTML=`<div class="center-label">NORTH POLE / CENTER / WINDOW</div><div class="center-map" aria-label="World to Door to Axis"><div class="center-axis axis-world"><span>WORLD</span><b>↘</b></div><div class="center-core"><div class="center-title">DOOR</div><div class="center-subtitle">FRAME = WINDOW</div><div class="center-core-note">WE LEARN THROUGH THE FRAME WE LOOK THROUGH.</div></div><div class="center-axis axis-axis"><b>↖</b><span>AXIS</span></div></div><div class="center-identity">TIM DOOLEY · POTATO OF LIFE</div><p class="center-description">The Door is the middle: the Frame and the Window at once. World opens from it toward observable life; Axis opens from it toward orientation, structure and relation. The interface stays at the Door so we can look through the frame and learn.</p><div class="center-records">${rs.map(r=>`<button class="center-record" type="button" data-center="${esc(r.id)}">${esc(r.label)}</button>`).join('')}</div>`;rs.forEach(r=>{const b=[...c.querySelectorAll('[data-center]')].find(x=>x.dataset.center===r.id);if(b)b.onclick=()=>{const found=state.records.find(x=>(x.canonical_id||x.id)===r.id||x.id===r.id);if(found)select(found,`CENTER/${r.id}`);else showCenterRecord(r);};});}
  function tree(){const t=$('#root-tree');t.innerHTML='';const world=state.manifest.branches.find(b=>b.id==='world'),axis=state.manifest.branches.find(b=>b.id==='axis');if(world)t.appendChild(branch(world,state.manifest.world.collections));if(axis)t.appendChild(branch(axis,state.manifest.axis.collections));}
  function collapse(){document.querySelectorAll('#root-tree details[open]').forEach(d=>d.open=false);state.expanded.clear();state.rendered.clear();save();}
  function roots(){document.querySelectorAll('#root-tree>details').forEach(d=>d.open=true);}
  async function init(){load();try{const [m,i]=await Promise.all([fetch(MANIFEST_URL,{cache:'no-store'}),fetch(DATA_URL,{cache:'no-store'})]);if(!m.ok)throw Error(`manifest HTTP ${m.status}`);state.manifest=await m.json();if(i.ok){const j=await i.json();state.records=Array.isArray(j.records)?j.records:[];}center();tree();const wanted=hashId()||state.selected;if(wanted){const r=state.records.find(x=>(x.canonical_id||x.id)===wanted||x.id===wanted);if(r)showDossier(r,'restored selection');}$('#root-status').textContent=`${state.records.length.toLocaleString()} indexed records · one center · WORLD + AXIS`;}catch(e){$('#root-status').textContent=`navigation index unavailable: ${e.message}`;$('#root-tree').innerHTML='<div class="tree-empty">The center is available. Build the generated root index to unfold the corpus.</div>';}}
  document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(a==='collapse-all')collapse();if(a==='expand-roots')roots();if(a==='reset-root'){collapse();close();scrollTo({top:0,behavior:'smooth'});}if(a==='close-dossier')close();});
  addEventListener('hashchange',()=>{const id=hashId();if(!id)return;const r=state.records.find(x=>(x.canonical_id||x.id)===id||x.id===id);if(r)showDossier(r,'URL selection');});
  init();
})();
