(() => {
  'use strict';
  const MANIFEST_URL='./data/root-navigation.json', RECORDS_URL='./data/root-record-index.json', BACKEND_URL='./data/backend.json', BRIDGE_URL='./data/frontend-atlas-bridge.json', STORAGE_KEY='potato-root-state-v10';
  const $=(s,r=document)=>r.querySelector(s), esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const state={manifest:null,records:[],backend:null,bridge:null,selected:null,expanded:new Set(),rendered:new Set(),sources:new Map()};
  const save=()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify({expanded:[...state.expanded],selected:state.selected}));}catch(_) {}};
  const load=()=>{try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');(x.expanded||[]).forEach(k=>state.expanded.add(k));state.selected=x.selected||null;}catch(_) {}};
  const hash=id=>history.replaceState(null,'',id?`${location.pathname}#node=${encodeURIComponent(id)}`:location.pathname), hashId=()=>new URLSearchParams(location.hash.replace(/^#/,'')).get('node');
  const unique=rows=>{const seen=new Set();return rows.filter(r=>{const k=r.canonical_id||`${r.source}:${r.id}:${JSON.stringify(r.path||[])}`;if(seen.has(k))return false;seen.add(k);return true;}).sort((a,b)=>String(a.name||a.id).localeCompare(String(b.name||b.id)));};
  function matches(r,c){
    if(c.all)return true;if(c.paths?.length)return c.paths.some(p=>(r.navigation_path||[]).join('/').toLowerCase()===String(p).toLowerCase());
    if(c.root&&String(r.repository_root).toLowerCase()!==String(c.root).toLowerCase())return false;if(c.types?.length&&!c.types.includes(String(r.type||'').toLowerCase()))return false;if(c.families?.length&&!c.families.includes(String(r.owner_family||'').toLowerCase()))return false;if(c.scales?.length&&!c.scales.includes(String(r.repository_scale||'').toLowerCase()))return false;if(c.role&&String(r.record_role||'').toLowerCase()!==String(c.role).toLowerCase())return false;
    if(c.terms?.length){const h=[r.id,r.name,r.description,r.source,r.owner_family,r.repository_layer,(r.navigation_path||[]).join(' ')].join(' ').toLowerCase();if(!c.terms.some(t=>h.includes(String(t).toLowerCase())))return false;}return !!(c.types||c.families||c.scales||c.role||c.terms);
  }
  function renderHtml(html,target){target.innerHTML='';if(!html)return false;try{const p=new DOMParser().parseFromString(String(html),'text/html'),s=p.body&&p.body.children.length?p.body:p.documentElement;[...s.childNodes].forEach(n=>target.appendChild(document.importNode(n,true)));return true;}catch(_){target.textContent=String(html);return true;}}
  function valueHtml(v){if(v===null||v===undefined)return '';if(typeof v==='string')return `<p>${esc(v)}</p>`;if(typeof v==='number'||typeof v==='boolean')return `<p>${esc(v)}</p>`;if(Array.isArray(v))return v.length?`<ul>${v.map(x=>`<li>${typeof x==='object'?`<code>${esc(JSON.stringify(x))}</code>`:esc(x)}</li>`).join('')}</ul>`:'';if(typeof v==='object')return Object.entries(v).map(([k,x])=>`<section><h3>${esc(pretty(k))}</h3>${valueHtml(x)}</section>`).join('');return '';}
  async function fetchJson(path){if(!path)return null;if(state.sources.has(path))return state.sources.get(path);try{const res=await fetch(`./${path}`,{cache:'no-store'});if(!res.ok)return null;const data=await res.json();state.sources.set(path,data);return data;}catch(_){return null;}}
  function atPath(root,path){let x=root;for(const p of path||[]){if(x==null)return null;x=x[p];}return x;}
  function relatedRows(id){const key=String(id||'').toLowerCase();return state.records.filter(r=>[r.id,r.canonical_id,r.name].join(' ').toLowerCase()===key).slice(0,40);}
  async function loadIntoFrame(r){
    const target=$('#frame-content');if(!target)return;target.innerHTML='<p class="loading">Opening record…</p>';const html=r.html||r.content_html||r.document_html;if(html&&renderHtml(html,target))return;
    const source=await fetchJson(r.source), original=source?atPath(source,r.path):null, rich=original&&typeof original==='object'?(original.html||original.content_html||original.document_html):null;if(rich&&renderHtml(rich,target))return;
    let body=`<div class="eyebrow">${esc((r.navigation_path||[]).join(' / ')||'RECORD')}</div><h1>${esc(r.name||r.id||'Record')}</h1>`;if(r.description)body+=`<p class="lead">${esc(r.description)}</p>`;body+=`<div class="meta"><span>${esc(r.type||'record')}</span><span>${esc(r.owner_family||'')}</span><span>${esc(r.repository_scale||'')}</span></div>`;
    if(original&&typeof original==='object'){const skip=new Set(['id','slug','key','name','title','label','description','definition','summary','html','content_html','document_html']);const details=Object.entries(original).filter(([k])=>!skip.has(k));if(details.length)body+=`<div class="source-record"><h2>Source record</h2>${details.map(([k,v])=>`<section><h3>${esc(pretty(k))}</h3>${valueHtml(v)}</section>`).join('')}</div>`;}
    const rel=relatedRows(r.canonical_id||r.id).filter(x=>(x.canonical_id||x.id)!==(r.canonical_id||r.id));if(rel.length)body+=`<section><h2>Other indexed material</h2><ul>${rel.map(x=>`<li><a href="#node=${encodeURIComponent(x.canonical_id||x.id)}">${esc(x.name||x.id)}</a></li>`).join('')}</ul></section>`;
    if(r.url||r.href)body+=`<p><a href="${esc(r.url||r.href)}" target="_blank" rel="noopener">Open external source ↗</a></p>`;if(r.source)body+=`<p><a href="./${esc(r.source)}" target="_blank" rel="noopener">Open source file ↗</a></p>`;target.innerHTML=body;
  }
  async function openDataset(label,path){const target=$('#frame-content');if(!target)return;target.innerHTML=`<div class="eyebrow">BACKEND DATA</div><h1>${esc(label)}</h1><p class="loading">Loading source…</p>`;const data=await fetchJson(path);if(data===null){target.innerHTML=`<div class="eyebrow">BACKEND DATA</div><h1>${esc(label)}</h1><p>Backend file could not be loaded.</p><p><code>${esc(path)}</code></p>`;return;}const keys=data&&typeof data==='object'?Object.keys(data):[];target.innerHTML=`<div class="eyebrow">BACKEND DATA</div><h1>${esc(label)}</h1><p class="lead">Directly exposed from the repository backend. ${keys.length?`${keys.length} top-level fields.`:''}</p><div class="source-record">${valueHtml(data)}</div><p><a href="./${esc(path)}" target="_blank" rel="noopener">Open raw JSON ↗</a></p>`;}
  function select(r){state.selected=r.canonical_id||r.id;hash(state.selected);loadIntoFrame(r);save();}
  function recordRow(r){const x=document.createElement('div');x.className='tree-entry record-entry';x.innerHTML=`<button class="tree-button" type="button">${esc(r.name||r.id)}</button>`;$('.tree-button',x).onclick=()=>select(r);return x;}
  function datasetRow(label,path){const x=document.createElement('div');x.className='tree-entry record-entry dataset-entry';x.innerHTML=`<button class="tree-button" type="button"><span>${esc(label)}</span><small>data</small></button>`;$('.tree-button',x).onclick=()=>openDataset(label,path);return x;}
  function renderCollection(details,c,branch){const key=`collection:${branch}:${c.id}`;if(state.rendered.has(key))return;state.rendered.add(key);const box=$('.tree-children',details),rows=unique(state.records.filter(r=>matches(r,c)));box.innerHTML='';const groups=new Map();rows.forEach(r=>{const g=(r.navigation_path||[branch,c.id,'RECORDS']).slice(-1)[0]||'RECORDS';if(!groups.has(g))groups.set(g,[]);groups.get(g).push(r);});if(rows.length>120){for(const [g,rs] of [...groups.entries()].sort()){const sub=document.createElement('details');sub.className='tree-subdir';sub.innerHTML=`<summary><span class="tree-name">${esc(g)}/</span><span class="tree-count">${rs.length}</span></summary><div class="tree-children"></div>`;rs.forEach(r=>$('.tree-children',sub).appendChild(recordRow(r)));box.appendChild(sub);}}else rows.forEach(r=>box.appendChild(recordRow(r)));if(!box.children.length)box.innerHTML='<div class="tree-empty">No indexed records in this branch.</div>';}
  function collection(c,branch){const d=document.createElement('details');d.className='tree-dir tree-collection';const key=`collection:${branch}:${c.id}`;const count=state.records.filter(r=>matches(r,c)).length;d.innerHTML=`<summary><span class="tree-name">${esc(c.label)}</span><span class="tree-count">${count}</span></summary><div class="tree-children"></div>`;d.addEventListener('toggle',()=>{if(d.open){state.expanded.add(key);renderCollection(d,c,branch);}else state.expanded.delete(key);save();});if(state.expanded.has(key)){d.open=true;renderCollection(d,c,branch);}return d;}
  function datasetDirectory(label,id,items){const d=document.createElement('details');d.className='tree-dir tree-collection';const key=`datasets:${id}`;d.innerHTML=`<summary><span class="tree-name">${esc(label)}</span><span class="tree-count">${items.length}</span></summary><div class="tree-children"></div>`;const box=$('.tree-children',d);items.forEach(([name,path])=>box.appendChild(datasetRow(name,path)));d.addEventListener('toggle',()=>{if(d.open)state.expanded.add(key);else state.expanded.delete(key);save();});if(state.expanded.has(key))d.open=true;return d;}
  function pretty(k){return String(k).replace(/([a-z])([A-Z])/g,'$1 $2').replace(/^./,x=>x.toUpperCase()).replace(/\bId\b/g,'ID');}
  function backendDirectories(branch){
    const e=state.backend?.endpoints||{};const out=[];const add=(label,keys)=>{const items=[...new Set(keys)].filter(k=>e[k]).map(k=>[pretty(k),e[k]]);if(items.length)out.push(datasetDirectory(label,label.toLowerCase().replace(/[^a-z0-9]+/g,'-'),items));};
    if(branch==='world'){
      add('ATLAS & MAPS/',['atlasManifest','nodes','countryNodes','countryStatic','countryAtlas','countryBlueprint','countryIndex','countryLayerManifest','countrySourceRegistry','indicatorCatalog','indicatorSourceMatrix']);
      add('GRAPHS & RELATIONS/',['globalGraphBridge','graphRegistry','graphCarvings','relationships','evidenceObservations','evidenceRelationships','evidenceMap','missingData','entanglement']);
      add('RESEARCH & FRONTIER/',['research','researchCarvings','projectWorkflow','backendCoverage']);
      add('CULTURE/',['cultureOntology','cultures']);
      add('BELIEF & RELIGION/',['beliefBackend','beliefRegistry','beliefIntegrity','religiousLayerManifest','religiousLayerMap','religiousDimensions','religiousSources','religiousComparativeLibrary']);
      add('SCRIPTURE & TEXTS/',['canonicalTexts','religiousTextLibrary','christianityIndex','bibleKjv','judaismTorah','taoismIndex','daoDeJing']);
    }else{
      add('POTATOISM/',['potatoismReligion','potatoismCosmology','potatoismLexicon','potatoismRelationships','mythicOntology','timDooleyCosmology']);
      add('AXIS & MODELS/',['axisTopology','tree','hawkinsScale']);
      add('PEOPLE & IDENTITY/',['peopleRegistry','peopleSeeds']);
      add('SYSTEMS & EXPANSION/',['expansionRegistry','globalGraphBridge','entanglement']);
    }return out;
  }
  function centerRecords(){
    const c=state.manifest?.center?.records||[];if(!c.length)return null;const d=document.createElement('details');d.className='tree-dir tree-center';d.innerHTML=`<summary><span class="tree-name">POTATO OF LIFE/</span><span class="tree-count">${c.length}</span></summary><div class="tree-children"></div>`;const box=$('.tree-children',d);
    const aliases={'tim-dooley':['tim-dooley','tim-dooley-father'],'potatoism':['potatoism','potato-of-life'],'thought':['thought','tim-dooley-thought'],'canon':['canon','potatoism-canonical-corpus']};
    c.forEach(item=>{let r=state.records.find(x=>(x.canonical_id||x.id)===item.id||x.id===item.id);for(const id of (aliases[item.id]||[])){if(r)break;r=state.records.find(x=>(x.canonical_id||x.id)===id||x.id===id);}if(r)box.appendChild(recordRow(r));else box.appendChild(datasetRow(item.label||item.id,'data/potatoism-canonical-corpus.json'));});return d;
  }
  function branch(b,cs){const d=document.createElement('details');d.className=`tree-dir tree-branch branch-${b.kind}`;const key=`branch:${b.id}`;d.innerHTML=`<summary><span class="tree-name">${esc(b.label)}</span><span class="tree-count">${state.records.filter(r=>r.repository_root===(b.kind==='axis'?'spirit':'matter')).length}</span></summary><div class="tree-children branch-children"></div>`;const box=$('.branch-children',d);cs.forEach(c=>box.appendChild(collection(c,b.id)));backendDirectories(b.id).forEach(x=>box.appendChild(x));d.addEventListener('toggle',()=>{if(d.open)state.expanded.add(key);else state.expanded.delete(key);save();});if(state.expanded.has(key)){d.open=true;}return d;}
  function tree(){const t=$('#root-tree');if(!t)return;t.innerHTML='';const center=centerRecords();if(center)t.appendChild(center);const world=state.manifest.branches.find(b=>b.id==='world'),axis=state.manifest.branches.find(b=>b.id==='axis');if(axis)t.appendChild(branch(axis,state.manifest.axis.collections));if(world)t.appendChild(branch(world,state.manifest.world.collections));}
  function collapse(){document.querySelectorAll('#root-tree details[open]').forEach(d=>d.open=false);state.expanded.clear();state.rendered.clear();save();}function roots(){document.querySelectorAll('#root-tree>details').forEach(d=>d.open=true);document.querySelectorAll('#root-tree>details').forEach(d=>{if(d.classList.contains('tree-branch')){const cs=d.querySelectorAll(':scope > .branch-children > details');cs.forEach(x=>{x.open=true;x.dispatchEvent(new Event('toggle'));});}});}
  function toggleFrame(){const f=$('#center-frame'),b=$('#frame-toggle');if(!f||!b)return;const h=f.classList.toggle('is-hidden');b.textContent=h?'show':'hide';b.setAttribute('aria-expanded',String(!h));}
  async function init(){load();const b=$('#frame-toggle');if(b)b.onclick=toggleFrame;try{const [m,i,k,g]=await Promise.all([fetch(MANIFEST_URL,{cache:'no-store'}),fetch(RECORDS_URL,{cache:'no-store'}),fetch(BACKEND_URL,{cache:'no-store'}),fetch(BRIDGE_URL,{cache:'no-store'})]);if(!m.ok)throw Error(`navigation manifest HTTP ${m.status}`);state.manifest=await m.json();if(i.ok){const j=await i.json();state.records=Array.isArray(j.records)?j.records:[];}if(k.ok)state.backend=await k.json();if(g.ok)state.bridge=await g.json();tree();const wanted=hashId()||state.selected;if(wanted){const r=state.records.find(x=>(x.canonical_id||x.id)===wanted||x.id===wanted);if(r)loadIntoFrame(r);}}catch(e){const t=$('#root-tree');if(t)t.innerHTML='<div class="tree-empty">Navigation unavailable.</div>';const target=$('#frame-content');if(target)target.innerHTML=`<h1>THE POTATO OF LIFE</h1><p>${esc(e.message||e)}</p>`;}}
  document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(a==='collapse-all')collapse();if(a==='expand-roots')roots();});addEventListener('hashchange',()=>{const id=hashId();if(!id)return;const r=state.records.find(x=>(x.canonical_id||x.id)===id||x.id===id);if(r)loadIntoFrame(r);});init();
})();
