const viewport=document.getElementById('viewport'),ruler=document.getElementById('ruler'),track=document.getElementById('track'),filters=document.getElementById('filters'),detail=document.getElementById('detail'),rangeLabel=document.getElementById('range-label'),countLabel=document.getElementById('event-count');
const YEAR=36, MONTH=3, START_YEAR=-3000, END_YEAR=2030;let events=[],enabled=new Set(['religion','geopolitical','historical','lore']);let offset=0,drag=false,startX=0,startOffset=0;
const slug=s=>String(s??'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const yearOf=d=>{if(!d)return null;const m=String(d).match(/^-?\d+/);return m?Number(m[0]):null};
const datePosition=d=>{const y=yearOf(d);if(y===null)return null;const m=String(d).match(/-(\d{2})/);const month=m?Number(m[1]):1;return (y-START_YEAR)*YEAR+(month-1)*MONTH};
const classify=(e,kind)=>{const t=(String(e.type||'')+' '+String(e.layer||'')).toLowerCase();if(kind==='religion')return /relig|foundat|tradition|faith/.test(t);if(kind==='geopolitical')return /geopolit|political|diplom|war|conflict|nato|state/.test(t);if(kind==='lore')return /lore|myth|potato|creative|project-myth/.test(t);return /histor|archaeolog|civiliz|textual|event/.test(t)};
function normaliseFoundation(x){return {id:x.id,date_start:x.historical_emergence||x.traditional_origin||x.seed,name:x.name||x.tradition_id,description:x.historical_emergence?`${x.tradition_id}: ${x.historical_emergence}. ${x.formation_markers?.join('; ')||''}`:'Foundation record',type:'religious-foundation',layer:'religion'}}
function add(arr,source){for(const x of arr||[]){const e={...x};let kind='historical';if(source==='religion')kind='religion';else if(source==='lore')kind='lore';else if(classify(e,'geopolitical'))kind='geopolitical';e.category=kind;e._pos=datePosition(e.date_start||e.date||e.year);if(e._pos!==null&&e.name)events.push(e)}}
async function json(path,fallback){try{const r=await fetch(path,{cache:'no-store'});return r.ok?await r.json():fallback}catch{return fallback}}
async function load(){const [ev,rf,lore,research]=await Promise.all([json('data/events.json',{events:[]}),json('data/religious-foundations.json',{records:[]}),json('data/potatoverse-lore.json',{records:[]}),json('data/research.json',{facts:[]})]);add(ev.events,'events');add(rf.records.map(normaliseFoundation),'religion');add(lore.records.map(x=>({...x,date_start:x.date_start||x.date||x.birth_date||x.year})),'lore');for(const x of research.facts||[]){if(x.date||x.date_start)add([x],'research')}events.sort((a,b)=>a._pos-b._pos);buildFilters();render()}
function buildFilters(){const defs=[['religion','Religious foundations'],['geopolitical','Geopolitical'],['historical','Historical'],['lore','Potatoverse lore']];filters.innerHTML=defs.map(([k,n])=>`<button class="filter" data-kind="${k}"><i class="dot ${k}"></i>${n}</button>`).join('');filters.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{const k=b.dataset.kind;if(enabled.has(k))enabled.delete(k);else enabled.add(k);b.classList.toggle('off',!enabled.has(k));render()})}
function render(){const visible=events.filter(e=>enabled.has(e.category));const totalWidth=(END_YEAR-START_YEAR+1)*YEAR;ruler.style.width=totalWidth+'px';track.style.width=totalWidth+'px';ruler.innerHTML='<div class="timeline-axis"></div>';for(let y=START_YEAR;y<=END_YEAR;y++){const x=(y-START_YEAR)*YEAR;ruler.insertAdjacentHTML('beforeend',`<div class="year-mark" style="left:${x}px"><span class="year-label">${y<0?Math.abs(y)+' BCE':y}</span></div>`);for(let m=1;m<=12;m++){const mx=x+(m-1)*MONTH;ruler.insertAdjacentHTML('beforeend',`<div class="month-mark" style="left:${mx}px"></div>`)} }track.innerHTML='';for(const e of visible){const x=e._pos;const y=128+(hash(e.id)%4)*28;const el=document.createElement('button');el.className=`event ${e.category}`;el.style.left=x+'px';el.style.top=y+'px';el.title=e.name;el.setAttribute('aria-label',e.name);el.innerHTML='<span class="event-label">'+esc(e.name)+'</span>';el.onpointerdown=ev=>{ev.stopPropagation();show(e)};track.appendChild(el)}ruler.style.transform=`translateX(${offset}px)`;track.style.transform=`translateX(${offset}px)`;const centerYear=START_YEAR+Math.round(((-offset)+viewport.clientWidth/2)/YEAR);rangeLabel.textContent=`Around ${centerYear<0?Math.abs(centerYear)+' BCE':centerYear}`;countLabel.textContent=`${visible.length} visible · ${events.length} total`}
function hash(s){let h=0;for(const c of String(s))h=(h*31+c.charCodeAt(0))|0;return Math.abs(h)}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function show(e){detail.innerHTML=`<p class="section-label">${esc(e.category.toUpperCase())} · ${esc(e.date_start||'DATE UNKNOWN')}</p><h2>${esc(e.name)}</h2><div class="detail-meta"><span>${esc(e.type||'event')}</span><span>${esc(e.layer||'archive')}</span></div><p>${esc(e.description||e.purpose||'This event is present in the timeline but needs a deeper event dossier.')}</p>${e.relations?.length?`<p><strong>Connections:</strong> ${esc(e.relations.join(' · '))}</p>`:''}${e.sources?.length?`<p><strong>Sources:</strong> ${esc(e.sources.map(s=>s.title||s.publisher).join(' · '))}</p>`:''}`}
viewport.onpointerdown=e=>{drag=true;startX=e.clientX;startOffset=offset;viewport.classList.add('dragging');viewport.setPointerCapture(e.pointerId)};viewport.onpointermove=e=>{if(!drag)return;offset=startOffset+(e.clientX-startX);const min=viewport.clientWidth-totalWidth();offset=Math.max(min,Math.min(0,offset));ruler.style.transform=`translateX(${offset}px)`;track.style.transform=`translateX(${offset}px)`;const centerYear=START_YEAR+Math.round(((-offset)+viewport.clientWidth/2)/YEAR);rangeLabel.textContent=`Around ${centerYear<0?Math.abs(centerYear)+' BCE':centerYear}`};viewport.onpointerup=()=>{drag=false;viewport.classList.remove('dragging');render()};viewport.onpointercancel=()=>{drag=false;viewport.classList.remove('dragging')};function totalWidth(){return(END_YEAR-START_YEAR+1)*YEAR}
document.getElementById('back').onclick=()=>{offset=Math.min(0,offset+viewport.clientWidth*.7);render()};document.getElementById('forward').onclick=()=>{offset=Math.max(viewport.clientWidth-totalWidth(),offset-viewport.clientWidth*.7);render()};document.getElementById('today').onclick=()=>{offset=-(2030-START_YEAR)*YEAR+viewport.clientWidth/2;render()};window.addEventListener('resize',render);load();