const viewport=document.getElementById('viewport'),ruler=document.getElementById('ruler'),track=document.getElementById('track'),filters=document.getElementById('filters'),detail=document.getElementById('detail'),rangeLabel=document.getElementById('range-label'),countLabel=document.getElementById('event-count'),lens=document.getElementById('timeline-lens'),jumpForm=document.getElementById('jump-form'),yearInput=document.getElementById('year-input');
const YEAR=24, MONTH=YEAR/12, START_YEAR=-3000, END_YEAR=2030;
let events=[],enabled=new Set(['religion','geopolitical','historical','lore']);let offset=0,drag=false,startX=0,startOffset=0,lensDrag=false,lensStartX=0,lensStartOffset=0,raf=0,lastRenderedFocus=null,velocity=0,lastX=0,lastTime=0,glideRaf=0;
const yearOf=d=>{if(!d)return null;const m=String(d).match(/^-?\d+/);return m?Number(m[0]):null};
const datePosition=d=>{const y=yearOf(d);if(y===null)return null;const m=String(d).match(/-(\d{2})/);const month=m?Number(m[1]):1;return (y-START_YEAR)*YEAR+(month-1)*MONTH};
const classify=(e,kind)=>{const t=(String(e.type||'')+' '+String(e.layer||'')).toLowerCase();if(kind==='religion')return /relig|foundat|tradition|faith/.test(t);if(kind==='geopolitical')return /geopolit|political|diplom|war|conflict|nato|state/.test(t);if(kind==='lore')return /lore|myth|potato|creative|project-myth/.test(t);return /histor|archaeolog|civiliz|textual|event/.test(t)};
function normaliseFoundation(x){return {id:x.id,date_start:x.historical_emergence||x.traditional_origin||x.seed,name:x.name||x.tradition_id,description:x.historical_emergence?`${x.tradition_id}: ${x.historical_emergence}. ${x.formation_markers?.join('; ')||''}`:'Foundation record',type:'religious-foundation',layer:'religion'}}
function add(arr,source){for(const x of arr||[]){const e={...x};let kind='historical';if(source==='religion')kind='religion';else if(source==='lore')kind='lore';else if(classify(e,'geopolitical'))kind='geopolitical';e.category=kind;e._pos=datePosition(e.date_start||e.date||e.year);if(e._pos!==null&&e.name)events.push(e)}}
async function json(path,fallback){try{const r=await fetch(path,{cache:'no-store'});return r.ok?await r.json():fallback}catch{return fallback}}
async function load(){const [ev,rf,lore,research]=await Promise.all([json('data/events.json',{events:[]}),json('data/religious-foundations.json',{records:[]}),json('data/potatoverse-lore.json',{records:[]}),json('data/research.json',{facts:[]})]);add(ev.events,'events');add(rf.records.map(normaliseFoundation),'religion');add(lore.records.map(x=>({...x,date_start:x.date_start||x.date||x.birth_date||x.year})),'lore');for(const x of research.facts||[]){if(x.date||x.date_start)add([x],'research')}events.sort((a,b)=>a._pos-b._pos);buildFilters();render(true)}
function buildFilters(){const defs=[['religion','Religious foundations'],['geopolitical','Geopolitical'],['historical','Historical'],['lore','Potatoverse lore']];filters.innerHTML=defs.map(([k,n])=>`<button class="filter" data-kind="${k}"><i class="dot ${k}"></i>${n}</button>`).join('');filters.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{const k=b.dataset.kind;if(enabled.has(k))enabled.delete(k);else enabled.add(k);b.classList.toggle('off',!enabled.has(k));render(true)})}
function hash(s){let h=0;for(const c of String(s))h=(h*31+c.charCodeAt(0))|0;return Math.abs(h)}
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function focusYear(){return Math.max(START_YEAR,Math.min(END_YEAR,START_YEAR+Math.round(((-offset)+viewport.clientWidth/2)/YEAR)))}
function formatYear(y){return y<0?Math.abs(y)+' BCE':y===0?'1 CE':y}
function applyTransforms(){ruler.style.transform=`translate3d(${offset}px,0,0)`;track.style.transform=`translate3d(${offset}px,0,0)`}
function scheduleLens(){cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{renderLens(events.filter(x=>enabled.has(x.category)));raf=0})}
function render(full=false){const visible=events.filter(e=>enabled.has(e.category));const total=totalWidth();if(full){ruler.style.width=total+'px';track.style.width=total+'px';ruler.innerHTML='<div class="timeline-axis"></div>';for(let y=START_YEAR;y<=END_YEAR;y++){const x=(y-START_YEAR)*YEAR;ruler.insertAdjacentHTML('beforeend',`<div class="year-mark" style="left:${x}px"><span class="year-label">${y<0?Math.abs(y)+' BCE':y===0?'1 CE':y}</span></div>`)}track.innerHTML='';for(const e of visible){const el=document.createElement('button');el.className=`event ${e.category}`;el.style.left=e._pos+'px';el.style.top=(128+(hash(e.id)%4)*28)+'px';el.title=e.name;el.setAttribute('aria-label',e.name);el.innerHTML='<span class="event-label">'+esc(e.name)+'</span>';el.onpointerdown=ev=>{ev.stopPropagation();show(e)};track.appendChild(el)}}applyTransforms();rangeLabel.textContent=`Focus: ${formatYear(focusYear())}`;countLabel.textContent=`${visible.length} visible · ${events.length} total`;scheduleLens()}
function renderLens(visible){const fy=focusYear();if(fy===lastRenderedFocus)return;lastRenderedFocus=fy;const yearStart=(fy-START_YEAR)*YEAR;const nearby=visible.filter(e=>Math.abs(e._pos-(yearStart+YEAR/2))<YEAR*3.5);let html=`<div class="lens-title">${formatYear(fy)}</div><div class="lens-months">`;for(let m=1;m<=12;m++)html+=`<span style="left:${((m-.5)/12)*100}%">${m}</span>`;html+='</div><div class="lens-axis"></div>';for(const e of nearby){const local=(e._pos-yearStart)/YEAR;const x=Math.max(5,Math.min(95,local*100));const y=104+(hash(e.id)%5)*19;html+=`<button class="lens-event ${e.category}" style="left:${x}%;top:${y}px" title="${esc(e.name)}" aria-label="${esc(e.name)}"></button>`}document.getElementById('lens-content').innerHTML=html;document.querySelectorAll('.lens-event').forEach((b,i)=>b.onclick=()=>show(nearby[i]));}
function show(e){detail.innerHTML=`<p class="section-label">${esc(e.category.toUpperCase())} · ${esc(e.date_start||'DATE UNKNOWN')}</p><h2>${esc(e.name)}</h2><div class="detail-meta"><span>${esc(e.type||'event')}</span><span>${esc(e.layer||'archive')}</span></div><p>${esc(e.description||e.purpose||'This event is present in the timeline but needs a deeper event dossier.')}</p>${e.relations?.length?`<p><strong>Connections:</strong> ${esc(e.relations.join(' · '))}</p>`:''}${e.sources?.length?`<p><strong>Sources:</strong> ${esc(e.sources.map(s=>s.title||s.publisher).join(' · '))}</p>`:''}`}
function totalWidth(){return(END_YEAR-START_YEAR+1)*YEAR}function clampOffset(v){return Math.max(viewport.clientWidth-totalWidth(),Math.min(0,v))}
function moveTimeline(clientX,startX,startO){offset=clampOffset(startO+(clientX-startX));applyTransforms();rangeLabel.textContent=`Focus: ${formatYear(focusYear())}`;scheduleLens()}
function stopGlide(){if(glideRaf){cancelAnimationFrame(glideRaf);glideRaf=0}velocity=0}
function glide(){stopGlide();let v=velocity;const friction=.955,minVelocity=.08;function step(){if(Math.abs(v)<minVelocity){glideRaf=0;velocity=0;render(true);return}offset=clampOffset(offset+v);if(offset===0||offset===viewport.clientWidth-totalWidth())v*=.55;v*=friction;velocity=v;applyTransforms();rangeLabel.textContent=`Focus: ${formatYear(focusYear())}`;scheduleLens();glideRaf=requestAnimationFrame(step)}glideRaf=requestAnimationFrame(step)}
function beginDrag(e,onLens=false){if(e.button!==undefined&&e.button!==0)return;if(e.target.closest('.lens-event'))return;e.preventDefault();e.stopPropagation();stopGlide();lastX=e.clientX;lastTime=performance.now();if(onLens){lensDrag=true;lensStartX=e.clientX;lensStartOffset=offset;lens.setPointerCapture(e.pointerId);lens.classList.add('dragging')}else{drag=true;startX=e.clientX;startOffset=offset;viewport.setPointerCapture(e.pointerId);viewport.classList.add('dragging')}}
function updateDrag(x){const now=performance.now(),dt=Math.max(8,now-lastTime),dx=x-lastX;velocity=(dx/dt)*16;lastX=x;lastTime=now}
viewport.addEventListener('pointerdown',e=>{if(e.target.closest('#timeline-lens'))return;beginDrag(e,false)});viewport.addEventListener('pointermove',e=>{if(drag){updateDrag(e.clientX);moveTimeline(e.clientX,startX,startOffset)}});viewport.addEventListener('pointerup',()=>{if(drag){drag=false;viewport.classList.remove('dragging');glide()}});viewport.addEventListener('pointercancel',()=>{drag=false;viewport.classList.remove('dragging');stopGlide()});
if(lens){lens.addEventListener('pointerdown',e=>beginDrag(e,true));lens.addEventListener('pointermove',e=>{if(lensDrag){updateDrag(e.clientX);moveTimeline(e.clientX,lensStartX,lensStartOffset)}});lens.addEventListener('pointerup',()=>{if(lensDrag){lensDrag=false;lens.classList.remove('dragging');glide()}});lens.addEventListener('pointercancel',()=>{lensDrag=false;lens.classList.remove('dragging');stopGlide()})}
viewport.addEventListener('wheel',e=>{e.preventDefault();stopGlide();offset=clampOffset(offset-e.deltaY*1.5-e.deltaX);applyTransforms();rangeLabel.textContent=`Focus: ${formatYear(focusYear())}`;scheduleLens()},{passive:false});viewport.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();stopGlide();offset=clampOffset(offset+YEAR*5);render(true)}if(e.key==='ArrowRight'){e.preventDefault();stopGlide();offset=clampOffset(offset-YEAR*5);render(true)}});
jumpForm.addEventListener('submit',e=>{e.preventDefault();const raw=yearInput.value.trim().replace(/,/g,'');if(!/^-?\d+$/.test(raw)){yearInput.setCustomValidity('Enter a year such as 500, 2020, or -500 for BCE.');yearInput.reportValidity();return}yearInput.setCustomValidity('');const year=Number(raw);if(year<START_YEAR||year>END_YEAR){yearInput.setCustomValidity(`Enter a year between ${Math.abs(START_YEAR)} BCE and ${END_YEAR}.`);yearInput.reportValidity();return}stopGlide();offset=clampOffset(-(year-START_YEAR)*YEAR+viewport.clientWidth/2-YEAR/2);render(true);yearInput.blur()});
document.getElementById('back').onclick=()=>{stopGlide();offset=clampOffset(offset+viewport.clientWidth*.7);render(true)};document.getElementById('forward').onclick=()=>{stopGlide();offset=clampOffset(offset-viewport.clientWidth*.7);render(true)};document.getElementById('today').onclick=()=>{stopGlide();const now=new Date().getFullYear();offset=clampOffset(-(now-START_YEAR)*YEAR+viewport.clientWidth/2-YEAR/2);render(true)};window.addEventListener('resize',()=>{stopGlide();render(true)});load();