const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let manifest=null,contextGraph={clusters:[]},active=null,cache=new Map();

async function loadJSON(path){if(cache.has(path))return cache.get(path);const r=await fetch(path);if(!r.ok)throw new Error(`${r.status} ${path}`);const data=await r.json();cache.set(path,data);return data}
function human(k){return String(k).replace(/[_-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function renderValue(v,depth=0){if(v===null||v===undefined)return'<div class="value">—</div>';if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')return`<div class="value">${esc(v)}</div>`;if(Array.isArray(v)){if(v.every(x=>['string','number','boolean'].includes(typeof x)))return `<div class="chips">${v.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div>`;return v.map(x=>`<div class="nested">${renderValue(x,depth+1)}</div>`).join('')}return Object.entries(v).map(([k,val])=>`<div class="kv"><div class="key">${esc(human(k))}</div>${renderValue(val,depth+1)}</div>`).join('')}
function branchById(id){return manifest.branches.find(b=>b.id===id)}
function relatedTo(id){return (manifest.relations||[]).filter(r=>r.from===id||r.to===id)}
function contextForBranch(id){return (contextGraph.clusters||[]).filter(c=>(c.branches||[]).includes(id))}
function relationCard(r,id){const other=r.from===id?r.to:r.from;const b=branchById(other);if(!b)return'';return `<button class="relation" data-branch="${esc(other)}"><span class="reltype">${esc(r.type)}</span><strong>${esc(b.title)}</strong><span>${esc(r.label)}</span></button>`}
function pathwayCard(p){return `<button class="pathway" data-pathway="${esc(p.id)}"><span class="pathlabel">PATHWAY</span><strong>${esc(p.title)}</strong><span>${esc(p.summary)}</span><div class="trail">${p.branches.map(id=>`<b>${esc(branchById(id)?.title||id)}</b>`).join('<i>→</i>')}</div></button>`}
function contextCard(c){return `<button class="contextcard" data-context="${esc(c.id)}"><span class="contextlabel">CONTEXT CLUSTER</span><strong>${esc(c.title)}</strong><span>${esc(c.summary)}</span><div class="chips compact">${(c.concepts||[]).slice(0,5).map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div></button>`}

async function showRecord(path){const target=$('#record-detail');target.innerHTML=`<div class="status">Loading ${esc(path)}…</div>`;try{const data=await loadJSON(path);const branches=manifest.branches.filter(b=>(b.records||[]).includes(path));const clusters=(contextGraph.clusters||[]).filter(c=>(c.records||[]).includes(path));target.innerHTML=`<article class="record"><div class="recordhead"><div><span class="recordtype">CANONICAL RECORD</span><h3>${esc(data.title||data.name||data.id||path)}</h3></div><code>${esc(path)}</code></div>${branches.length?`<div class="recordcontext"><span>Appears in</span>${branches.map(b=>`<button data-branch="${esc(b.id)}">${esc(b.title)}</button>`).join('')}</div>`:''}${clusters.length?`<div class="section mini"><h3>Context clusters</h3><div class="contexts">${clusters.map(contextCard).join('')}</div></div>`:''}${renderValue(data)}</article>`;bindDynamic();history.replaceState(null,'',`#record=${encodeURIComponent(path)}`)}catch(e){target.innerHTML=`<div class="record"><div class="status">Could not load ${esc(path)}: ${esc(e.message)}</div></div>`}}

function branchHTML(b){const children=(b.children||[]).map(x=>`<span class="chip">${esc(x)}</span>`).join('');const records=(b.records||[]).map(p=>`<button class="record-link" data-record="${esc(p)}"><span class="recordtype">OPEN RECORD</span><strong>${esc(p.split('/').pop().replace(/\.(json|md)$/,''))}</strong><code>${esc(p)}</code></button>`).join('');const dirs=[...(b.directories||[]),...(b.directory?[b.directory]:[])];const related=relatedTo(b.id).map(r=>relationCard(r,b.id)).join('');const contexts=contextForBranch(b.id).map(contextCard).join('');return `<div class="branchhero"><span class="branchmark">${esc(b.title.slice(0,1))}</span><div><div class="eyebrow">Connected branch</div><h2>${esc(b.title)}</h2><p class="summary">${esc(b.description||'')}</p></div></div>${contexts?`<div class="section"><h3>Contextual constellations</h3><div class="contexts">${contexts}</div></div>`:''}${children?`<div class="section"><h3>Canonical substructure</h3><div class="chips">${children}</div></div>`:''}${related?`<div class="section"><h3>Relationships</h3><div class="relations">${related}</div></div>`:''}${records?`<div class="section"><h3>Canonical records</h3>${records}</div>`:''}${dirs.length?`<div class="section"><h3>Mapped directories</h3>${dirs.map(d=>`<div class="directory"><code>${esc(d)}</code></div>`).join('')}</div>`:''}<div id="record-detail"></div>`}

function rootHTML(){const paths=(manifest.pathways||[]).map(pathwayCard).join('');const contexts=(contextGraph.clusters||[]).map(contextCard).join('');const relationCount=(manifest.relations||[]).length;return `<div class="rootintro"><div><div class="eyebrow">Relationship-first knowledge system</div><h2>${esc(manifest.root.title)}</h2><p class="summary">${esc(manifest.root.summary)}</p></div><div class="rootstats"><div><strong>${manifest.branches.length}</strong><span>branches</span></div><div><strong>${relationCount}</strong><span>explicit relations</span></div><div><strong>${(contextGraph.clusters||[]).length}</strong><span>context clusters</span></div></div></div>${contexts?`<div class="section"><h3>Contextual constellations</h3><p class="sectionnote">These clusters combine records because their structures illuminate one another. They preserve whether each layer is canonical, comparative, historical, analytical or speculative.</p><div class="contexts">${contexts}</div></div>`:''}${paths?`<div class="section"><h3>Ways through the archive</h3><div class="pathways">${paths}</div></div>`:''}<div class="section"><h3>Branch field</h3><div class="branchfield">${manifest.branches.map(b=>`<button class="branchnode" data-branch="${esc(b.id)}"><span>${esc(b.title)}</span><small>${esc((b.children||[]).slice(0,4).join(' · ')||b.description)}</small></button>`).join('')}</div></div><div class="section"><h3>Architecture rules</h3><div class="chips">${manifest.principles.map(p=>`<span class="chip">${esc(p)}</span>`).join('')}</div></div><div class="section"><h3>Root record</h3><button class="record-link" data-record="${esc(manifest.root.record)}"><span class="recordtype">OPEN ROOT</span><strong>Potato of Life</strong><code>${esc(manifest.root.record)}</code></button></div><div id="record-detail"></div>`}

function showContext(id){const c=(contextGraph.clusters||[]).find(x=>x.id===id);if(!c)return;const branchButtons=(c.branches||[]).map(id=>{const b=branchById(id);return b?`<button class="branchnode" data-branch="${esc(id)}"><span>${esc(b.title)}</span><small>${esc(b.description)}</small></button>`:''}).join('');const records=(c.records||[]).map(p=>`<button class="record-link" data-record="${esc(p)}"><span class="recordtype">OPEN CONTEXT RECORD</span><strong>${esc(p.split('/').pop().replace(/\.json$/,''))}</strong><code>${esc(p)}</code></button>`).join('');$('#reader').innerHTML=`<div class="eyebrow">Context cluster</div><h2>${esc(c.title)}</h2><p class="summary">${esc(c.summary)}</p><div class="section"><h3>Concepts in this constellation</h3><div class="chips">${(c.concepts||[]).map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div></div><div class="section"><h3>Epistemic layers</h3><div class="chips">${(c.epistemic_mix||[]).map(x=>`<span class="chip epistemic">${esc(human(x))}</span>`).join('')}</div></div><div class="section"><h3>Connected branches</h3><div class="branchfield">${branchButtons}</div></div><div class="section"><h3>Records that carry this context</h3>${records}</div><div id="record-detail"></div>`;bindDynamic();history.replaceState(null,'',`#context=${encodeURIComponent(id)}`)}

function bindDynamic(){document.querySelectorAll('[data-record]').forEach(b=>b.addEventListener('click',()=>showRecord(b.dataset.record)));document.querySelectorAll('[data-branch]').forEach(b=>b.addEventListener('click',()=>selectBranch(b.dataset.branch)));document.querySelectorAll('[data-pathway]').forEach(btn=>btn.addEventListener('click',()=>showPathway(btn.dataset.pathway)));document.querySelectorAll('[data-context]').forEach(btn=>btn.addEventListener('click',()=>showContext(btn.dataset.context)))}
function showPathway(id){const p=(manifest.pathways||[]).find(x=>x.id===id);if(!p)return;const steps=p.branches.map((bid,i)=>{const b=branchById(bid);return `<button class="pathstep" data-branch="${esc(bid)}"><span>${String(i+1).padStart(2,'0')}</span><div><strong>${esc(b.title)}</strong><small>${esc(b.description)}</small></div></button>`}).join('');$('#reader').innerHTML=`<div class="eyebrow">Guided pathway</div><h2>${esc(p.title)}</h2><p class="summary">${esc(p.summary)}</p><div class="pathsteps">${steps}</div>`;bindDynamic();history.replaceState(null,'',`#path=${encodeURIComponent(id)}`)}
function selectBranch(id){active=id;document.querySelectorAll('.branchbtn').forEach(b=>b.classList.toggle('active',b.dataset.id===id));const reader=$('#reader');if(id==='root')reader.innerHTML=rootHTML();else{const b=branchById(id);reader.innerHTML=branchHTML(b)}bindDynamic();history.replaceState(null,'',id==='root'?'#root':`#branch=${encodeURIComponent(id)}`)}
function buildNav(){const nav=$('#branches');nav.innerHTML=manifest.branches.map(b=>`<button class="branchbtn" data-id="${esc(b.id)}"><span class="title">${esc(b.title)}</span><span class="desc">${esc(b.description||'')}</span></button>`).join('');nav.querySelectorAll('.branchbtn').forEach(b=>b.addEventListener('click',()=>selectBranch(b.dataset.id)));$('#rootbtn').addEventListener('click',()=>selectBranch('root'))}
function applySearch(q){q=q.trim().toLowerCase();document.querySelectorAll('.branchbtn').forEach(btn=>{const b=branchById(btn.dataset.id);const rels=relatedTo(b.id).map(r=>r.label).join(' ');const ctx=contextForBranch(b.id).flatMap(c=>[c.title,c.summary,...(c.concepts||[])]).join(' ');const hay=[b.title,b.description,...(b.children||[]),...(b.records||[]),rels,ctx].join(' ').toLowerCase();btn.style.display=!q||hay.includes(q)?'block':'none'});if(q.length>2){const matches=(contextGraph.clusters||[]).filter(c=>[c.title,c.summary,...(c.concepts||[]),...(c.epistemic_mix||[])].join(' ').toLowerCase().includes(q));if(matches.length){$('#reader').innerHTML=`<div class="eyebrow">Context search</div><h2>Context matches</h2><p class="summary">Search now reaches concepts and contextual constellations, not only branch titles.</p><div class="contexts">${matches.map(contextCard).join('')}</div>`;bindDynamic()}}}

async function init(){try{[manifest,contextGraph]=await Promise.all([loadJSON('manifest.json'),loadJSON('knowledge/indexes/context-graph.json').catch(()=>({clusters:[]}))]);buildNav();const hash=location.hash;if(hash.startsWith('#branch=')){const id=decodeURIComponent(hash.slice(8));selectBranch(branchById(id)?id:'root')}else if(hash.startsWith('#record=')){selectBranch('root');await showRecord(decodeURIComponent(hash.slice(8)))}else if(hash.startsWith('#path=')){showPathway(decodeURIComponent(hash.slice(6)))}else if(hash.startsWith('#context=')){showContext(decodeURIComponent(hash.slice(9)))}else selectBranch('root');$('#q').addEventListener('input',e=>applySearch(e.target.value))}catch(e){$('#reader').innerHTML=`<div class="status">Archive failed to load: ${esc(e.message)}</div>`}}
init();