(()=>{
'use strict';

const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asArray=value=>Array.isArray(value)?value:(value==null?[]:[value]);
const unique=values=>[...new Set(values.filter(Boolean))];
const norm=value=>String(value||'').toLowerCase();
const safeJSON=async url=>{try{const response=await fetch(url);return response.ok?await response.json():null}catch(error){console.warn('Bible comparison data load failed',url,error);return null}};
const firstYear=value=>{const match=String(value||'').match(/(?:19|20)\d{2}/);return match?Number(match[0]):null};
const dateKey=value=>{const match=String(value||'').trim().match(/((?:19|20)\d{2})(?:-(\d{2})(?:-(\d{2}))?)?/);if(!match)return '';return match[3]?`${match[1]}-${match[2]}-${match[3]}`:match[2]?`${match[1]}-${match[2]}`:match[1]};
const slug=value=>norm(value).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90)||'relation';
const groupByDate=(items,getDate)=>{const map=new Map();asArray(items).forEach(item=>{const key=dateKey(getDate(item));if(!key)return;if(!map.has(key))map.set(key,[]);map.get(key).push(item)});return map};

const PATHS={
 field:'../../knowledge/traditions/biblical-syncretism-field.json',
 atlas:'../../knowledge/traditions/biblical-overlap-atlas.json',
 fragments:'../../knowledge/traditions/biblical-passage-fragments.json',
 attestations:'../../knowledge/timeline/tim-biblical-vocabulary-attestation-ledger.json',
 reverse:'../../knowledge/timeline/reverse-biblical-overlap-timeline-2025-2026.json',
 occurrences:'../../data/evidence/rational-potato-x-occurrence-ledger-2024-2026.json',
 timeline:'../../data/timeline-events.json'
};

const CORE_RELATION_ORDER=[
 'childhood-cultivation-gardener-precursor-1992',
 'christian-vocabulary-enters-age12-1999',
 'light-collapse-return-2003',
 'motorcycle-blood-unbroken-bones-2005',
 'care-home-rise-walk-witness-2009-era',
 'tree-ordeal-hanging-curse-redemption-2011',
 'yahya-john-lamb-recognition-2016',
 'crucify-me-hesitation-trial-neighbor-2017',
 'persona-death-old-new-self-2018',
 'son-meme-crucifixion-burial-2019-2020',
 'potato-birth-hidden-life-2020-12-25',
 'chosen-gentile-potato-2024-10-02',
 'potatoes-die-for-sins-2024-10-03',
 'potato-axis-turning-ladder-2025-04-21',
 'self-resurrection-witnesses-2025-09-30',
 'father-after-crucified-son-2025-12-17',
 'bread-door-tomb-resurrection-2026-04-23',
 'ladder-door-specialization-2026-05-19',
 'john14-15-house-thomas-way-gardener-vine-sequence-2026-07-23',
 'passover-house-door-lamb-threshold-2026-07-24',
 'son-cornerstone-2026-08-17',
 'psalm82-gods-sons-mosthigh-justice-test-2026-09-13',
 'emmaus-return-before-recognition-bread',
 'mary-gardener-misrecognition-return',
 'acts-forty-days-resurrection-to-ascension',
 'john21-shore-recognition-feeding-after-return',
 'oct1-father-internet-ladder-swamp',
 'oct1-prophetic-name-witness-deaf-blind',
 'oct1-jesus-dead-countertext'
]
const CORE_RELATION_IDS=new Set(CORE_RELATION_ORDER);
const TIM_LIVED_ACTORS=new Set(['tim','son','tim-shared','son-shared']);
const CORE_RELATION_RANK=new Map(CORE_RELATION_ORDER.map((id,index)=>[id,index]));

const VIEW_DEFS={
 core:{label:'Core Tim / Son story'},
 jesus:{label:'Jesus / Gospel parallels',terms:['jesus','christ','son','thomas','messiah','lion','lamb','cross','crucif','resurrection','tomb','bread','grain','cornerstone','son of man']},
 'tim-said':{label:'What Tim said',modes:['tim-explicit','public-occurrence','conversation-recovery','book-explicit']},
 'tim-lived':{label:'Tim / Son story',terms:['tree ordeal','prison','custody','rejected','death','return','burial','tomb','resurrection','crucif','cross','root','garden','stone','ladder','carry','orphan']},
 prophecy:{label:'Prophecy / public signs',terms:['prophecy','foresight','prediction','predicted','warning before']},
 'father-house':{label:'Father / House',terms:['father','house','gardener','vinedresser','throne','most high','seat','rooms','mansions','source','davidic house']},
 'door-ladder':{label:'Door / Ladder',terms:['door','gate','ladder','needle','heaven','jacob','guardians','way','veil','threshold']},
 'death-return':{label:'Death / return',terms:['death','dead','crucif','tomb','burial','resurrection','return','grain','seed','womb']},
 'revelation-zion':{label:'Revelation / Zion',terms:['revelation','zion','new jerusalem','144000','144,000','lion','lamb','root of david','throne','river','tree of life','north','zechariah']},
 'counter-texts':{label:'Counter-texts',counter:true},
 all:{label:'Everything'}
};

const ARC_DEFS={
 'father-house':{label:'Father / House / Source',terms:['father','house','source','builder','throne','gardener','vinedresser','rooms']},
 'door-ladder':{label:'Door / Gate / Ladder',terms:['door','gate','ladder','veil','threshold','pass','open','shut','way']},
 'death-return':{label:'Seed / Death / Return',terms:['death','seed','grain','burial','tomb','return','resurrection','rise','die']},
 'god-presence':{label:'God / Presence',terms:['god','presence','temple','contain','dwell','indwell','manifest','hidden']},
 'garden-spirit':{label:'Garden / Spirit',terms:['garden','spirit','flow','water','prune','grow','repair','restore','feed','root']}
};

const BIBLE_BOOK_ORDER=['Genesis','Exodus','Leviticus','Numbers','Deuteronomy','Joshua','Judges','Ruth','1 Samuel','2 Samuel','1 Kings','2 Kings','1 Chronicles','2 Chronicles','Ezra','Nehemiah','Esther','Job','Psalms','Psalm','Proverbs','Ecclesiastes','Song of Solomon','Isaiah','Jeremiah','Lamentations','Ezekiel','Daniel','Hosea','Joel','Amos','Obadiah','Jonah','Micah','Nahum','Habakkuk','Zephaniah','Haggai','Zechariah','Malachi','Matthew','Mark','Luke','John','Acts','Romans','1 Corinthians','2 Corinthians','Galatians','Ephesians','Philippians','Colossians','1 Thessalonians','2 Thessalonians','1 Timothy','2 Timothy','Titus','Philemon','Hebrews','James','1 Peter','2 Peter','1 John','2 John','3 John','Jude','Revelation'];
const BIBLE_BOOK_RANK=new Map(BIBLE_BOOK_ORDER.map((book,index)=>[book,index]));

const OPERATOR_TERMS={contain:['contain','container','temple cannot','house'],dwell:['dwell','dwelling','indwell','house'],veil:['veil','flesh','curtain'],pass:['pass','way','threshold','through'],open:['open','door','gate','key'],shut:['shut','close','closed'],send:['send','sent'],carry:['carry','carried','burden','vessel'],release:['release','let go','hold'],root:['root','rooted','graft'],prune:['prune','vinedresser','branch'],flow:['flow','river','water','spirit'],feed:['feed','bread','manna','nourish'],repair:['repair','breach','restore paths'],restore:['restore','new creation','healing','return'],judge:['judge','judgment'],plant:['plant','seed','sow'],grow:['grow','growth','fruit'],die:['death','die','dead','burial','tomb'],rise:['rise','resurrection','return','stand'],remember:['remember','memory'],inherit:['inherit','inheritance'],name:['name','called','title']};

function rowText(row){return [row.id,row.title,row.actor,row.project_anchor,row.project_context,row.project_development,row.overlap,row.sequence,row.project_value,row.discovery_mode,row.relation_class,row.classification,row.source_direction,row.counter_text,row.source_correction,row.difference,row.boundary,row.provenance,...asArray(row.biblical_refs),...asArray(row.motifs),...asArray(row.relation_arguments),...asArray(row.possible_meaning),...asArray(row.weaknesses),...asArray(row.operators),...asArray(row.mechanisms)].join(' ').toLowerCase()}
function inferEvidence(row){if(row.evidence_kind)return row.evidence_kind;if(row.source_kind==='canonical-overlap-atlas')return 'canonical comparative synthesis';if(row.discovery_mode==='public-occurrence')return 'public project occurrence';if(row.discovery_mode==='conversation-recovery')return 'recovered conversation';if(row.discovery_mode==='book-explicit')return 'Great Book / project text';if(row.discovery_mode==='tim-explicit'||row.discovery_mode==='tim-led')return 'Tim/project explicit material';return 'canonical relation record'}
function inferOperators(row){const explicit=asArray(row.operators),hay=rowText(row),inferred=Object.entries(OPERATOR_TERMS).filter(([,terms])=>terms.some(term=>hay.includes(term))).map(([op])=>op);return unique([...explicit,...inferred]).slice(0,8)}
function relationMechanisms(row){return unique([...asArray(row.mechanisms),row.classification,row.relation_class].filter(Boolean))}
function normalizeFieldRow(row){return {...row,title:row.title||String(row.project_anchor||row.id).slice(0,110),biblical_refs:asArray(row.biblical_refs),motifs:asArray(row.motifs),relation_arguments:asArray(row.relation_arguments),weaknesses:asArray(row.weaknesses),owners:unique([...asArray(row.owners),...asArray(row.source_owners)]),source_owners:asArray(row.source_owners),occurrence_ids:asArray(row.occurrence_ids),timeline_event_ids:asArray(row.timeline_event_ids),evidence_kind:inferEvidence(row),operators:inferOperators(row),mechanisms:relationMechanisms(row)}}
function normalizeOverlap(item,updated){return normalizeFieldRow({id:`atlas-${item.id||slug(item.potatoverse_motif)}`,title:item.id?item.id.replaceAll('-',' '):item.potatoverse_motif,date:`research synthesis · ${updated||'2026'}`,actor:'project-research',project_anchor:item.potatoverse_motif||item.project_value||item.id,biblical_refs:asArray(item.biblical_text||item.texts),motifs:[item.potatoverse_motif,item.id],relation_arguments:unique([item.overlap,item.sequence,item.project_value,...asArray(item.possible_meaning)]),weaknesses:unique([item.difference,item.boundary]),counter_text:item.counter_text,discovery_mode:'archive-later',relation_class:item.classification||'later-structural-parallel',classification:item.classification,strength:Number(item.strength)||4,source_direction:'This relation is a later canonical comparative synthesis unless an earlier project-side date is separately documented. Do not backdate the verse-level mapping into the earlier event.',provenance:'Promoted canonical synthesis from biblical-overlap-atlas.json',owners:['knowledge/traditions/biblical-overlap-atlas.json'],source_kind:'canonical-overlap-atlas'})}
function normalizeMetaArc(item,updated){return normalizeFieldRow({id:`arc-${item.id}`,title:item.id.replaceAll('-',' '),date:`research synthesis · ${updated||'2026'}`,actor:'project-research',project_anchor:item.project_value||item.sequence,biblical_refs:asArray(item.texts),motifs:[item.id],relation_arguments:unique([item.sequence,item.project_value]),weaknesses:asArray(item.boundary),discovery_mode:'archive-later',relation_class:'cross-text-structural-synthesis',strength:Number(item.strength)||5,source_direction:'This is a cross-text canonical synthesis assembled after the underlying biblical texts and project motifs; it is not an at-the-time project quotation.',provenance:'Canonical meta-arc from biblical-overlap-atlas.json',owners:['knowledge/traditions/biblical-overlap-atlas.json'],source_kind:'canonical-overlap-atlas'})}
function fragmentIndex(fragmentData){const map=new Map();asArray(fragmentData&&fragmentData.fragments).forEach(fragment=>unique([fragment.reference,...asArray(fragment.matches)]).forEach(key=>{if(!key)return;if(!map.has(key))map.set(key,[]);map.get(key).push(fragment)}));return map}
function bookFromRef(reference){const ref=String(reference||'').trim(),match=ref.match(/^((?:[1-3]\s+)?[A-Za-z]+(?:\s+[A-Za-z]+)?)\s+\d/);return match?match[1]:ref.split(/\s+\d/)[0]}
function bibleOrderKey(row){const refs=asArray(row.biblical_refs);if(!refs.length)return 9999;return Math.min(...refs.map(ref=>BIBLE_BOOK_RANK.get(bookFromRef(ref))??9999))}
function ownerHref(owner){if(!owner)return '#';if(/^https?:\/\//.test(owner))return owner;return '../../'+owner.split('/').map(encodeURIComponent).join('/')}
function matchesTerms(row,terms){const text=rowText(row);return terms.some(term=>text.includes(term))}
function matchesView(row,view){const def=VIEW_DEFS[view]||VIEW_DEFS.core;if(view==='all')return true;if(view==='core')return CORE_RELATION_IDS.has(row.id);if(view==='tim-lived')return CORE_RELATION_IDS.has(row.id)||TIM_LIVED_ACTORS.has(norm(row.actor));if(def.counter)return asArray(row.weaknesses).length>0||Boolean(row.counter_text||row.source_correction||row.difference||row.boundary);if(def.modes&&def.modes.includes(row.discovery_mode))return true;return def.terms?matchesTerms(row,def.terms):true}
function matchesFocus(row,focus){const [kind,id]=String(focus||'view:core').split(':');if(kind==='arc')return matchesTerms(row,(ARC_DEFS[id]||{terms:[]}).terms);return matchesView(row,id)}
function focusLabel(focus){const [kind,id]=String(focus||'view:core').split(':');return kind==='arc'?(ARC_DEFS[id]?.label||id):(VIEW_DEFS[id]?.label||'Core Tim / Son story')}
function exactQuotes(row,evidence){return unique([...asArray(row.project_quote),...asArray(row.exact_wording),...asArray(row.public_wording),...asArray(row.recovered_wording),row.quote,...asArray(row.occurrence_ids).map(id=>evidence.occurrenceById.get(id)?.quote)]).filter(Boolean)}
function exactAvailable(row,evidence){return exactQuotes(row,evidence).length>0}
function whyText(row){return unique([...asArray(row.relation_arguments),row.overlap,row.project_value,...asArray(row.possible_meaning)]).filter(Boolean).slice(0,3).join(' ')}
function mismatchText(row){return unique([...asArray(row.weaknesses),row.counter_text,row.source_correction,row.difference,row.boundary]).filter(Boolean).slice(0,3).join(' ')}
function scriptureHTML(row,fragmentMap){const refs=asArray(row.biblical_refs),fragments=[];refs.forEach(ref=>asArray(fragmentMap.get(ref)).forEach(fragment=>{if(!fragments.some(x=>x.reference===fragment.reference&&x.text===fragment.text))fragments.push(fragment)}));if(fragments.length)return fragments.slice(0,4).map(fragment=>`<blockquote class="bible-quote">${esc(fragment.text)}<cite>${esc(fragment.reference)} · ${esc(fragment.translation||'World English Bible')}</cite></blockquote>`).join('');return `<p class="no-fragment"><strong>Scripture scope:</strong> ${esc(refs.join(' · ')||'broader biblical tradition')}</p>`}
function wordingForAttestation(entry){return unique([...asArray(entry.wording),entry.wording_summary,...asArray(entry.signals)].filter(Boolean))}
function compactSummary(value,max=260){const text=String(value||'').trim();if(!text)return '';const first=text.match(/^(.{1,260}?[.!?])(?:\s|$)/);const picked=(first&&first[1])||text;return picked.length>max?picked.slice(0,max-1).trimEnd()+'…':picked}
function humanize(value){return String(value||'').replaceAll('-',' ').replace(/\b\w/g,char=>char.toUpperCase())}

function evidenceContextHTML(row,evidence){
 const key=dateKey(row.date||row.timestamp),directOccurrenceIds=asArray(row.occurrence_ids),sameDateOccurrences=(evidence.occurrenceByDate.get(key)||[]).filter(item=>!directOccurrenceIds.includes(item.id)),attestations=evidence.attestationByDate.get(key)||[],reversals=evidence.reverseByDate.get(key)||[],explicitEventIds=asArray(row.timeline_event_ids),explicitEvents=explicitEventIds.map(id=>evidence.eventById.get(id)).filter(Boolean),sameDateEvents=(evidence.timelineByDate.get(key)||[]).filter(event=>!explicitEventIds.includes(event.id));
 const sameDateHtml=sameDateOccurrences.length?`<section class="context-card full"><h4>Same-date public wording</h4><p>Circumstantial context only; same-date wording is not treated as direct proof.</p>${sameDateOccurrences.slice(0,5).map(item=>`<blockquote>${esc(item.quote)}<cite>${esc(item.id)} · ${esc(asArray(item.tags).join(' · '))}</cite></blockquote>`).join('')}</section>`:'';
 const attestationHtml=attestations.length?`<section class="context-card full"><h4>Biblical vocabulary / revelation context</h4>${attestations.slice(0,5).map(item=>`${wordingForAttestation(item).map(text=>`<blockquote>${esc(text)}</blockquote>`).join('')}${item.development?`<p>${esc(item.development)}</p>`:''}`).join('')}</section>`:'';
 const reverseHtml=reversals.length?`<section class="context-card"><h4>Tim-first / later biblical recognition</h4>${reversals.slice(0,4).map(item=>`<p><strong>${esc(item.status||'comparison')}</strong> — ${esc(item.significance||item.finding||'')}</p>`).join('')}</section>`:'';
 const timelineEvents=[...explicitEvents,...sameDateEvents].slice(0,5),timelineHtml=timelineEvents.length?`<section class="context-card"><h4>Timeline context</h4>${timelineEvents.map(event=>`<p><strong>${esc(event.date||event.timestamp||'')}</strong> ${esc(event.title||event.summary||event.id||'project event')}</p>`).join('')}</section>`:'';
 return sameDateHtml+attestationHtml+reverseHtml+timelineHtml;
}

function relatedRows(row,sequence){
 const rowMotifs=new Set(asArray(row.motifs).map(norm)),rowOps=new Set(asArray(row.operators).map(norm)),rowBooks=new Set(asArray(row.biblical_refs).map(bookFromRef));
 return sequence.filter(candidate=>candidate.id!==row.id).map(candidate=>{let score=0;asArray(candidate.motifs).forEach(x=>{if(rowMotifs.has(norm(x)))score+=3});asArray(candidate.operators).forEach(x=>{if(rowOps.has(norm(x)))score+=2});asArray(candidate.biblical_refs).map(bookFromRef).forEach(x=>{if(rowBooks.has(x))score+=2});if(candidate.relation_class&&candidate.relation_class===row.relation_class)score+=1;return {row:candidate,score}}).filter(item=>item.score>0).sort((a,b)=>b.score-a.score||Number(b.row.strength||0)-Number(a.row.strength||0)).slice(0,4);
}

function renderActiveRelation(row,fragmentMap,evidence,sequence){
 if(!row)return '<div class="empty">No canonical comparisons match this study state. Clear a filter or choose another focus.</div>';
 const why=whyText(row)||'This relation is retained because the canonical comparison field records a meaningful lexical, narrative, structural, ethical or theological connection between the project-side anchor and the cited biblical material.';
 const mismatch=mismatchText(row),operators=asArray(row.operators),mechanisms=asArray(row.mechanisms).slice(0,5),owners=unique([...asArray(row.owners),...asArray(row.source_owners)]).slice(0,10).map(owner=>`<a href="${esc(ownerHref(owner))}">${esc(owner.split('/').pop())}</a>`).join(''),exact=exactQuotes(row,evidence),evidenceHtml=evidenceContextHTML(row,evidence),related=relatedRows(row,sequence);
 const argument=row.relation_argument&&typeof row.relation_argument==='object'?row.relation_argument:{};
 const projectSequence=asArray(argument.project_sequence).filter(Boolean),biblicalSequence=asArray(argument.biblical_sequence).filter(Boolean),correspondences=asArray(argument.correspondences).filter(Boolean),maximumClaim=argument.maximum_claim||row.maximum_claim||'';
 const projectContext=row.project_context||row.project_anchor,sceneDetail=row.what_happened&&row.what_happened!==projectContext?row.what_happened:'',laterMeaning=row.project_development||argument.why_it_matters||argument.why_dense;
 const scriptureContext=row.scripture_context&&typeof row.scripture_context==='object'?row.scripture_context:{},scriptureContextItems=unique([scriptureContext.literary_context,scriptureContext.historical_context,scriptureContext.canonical_context]).filter(Boolean);
 const sceneContext=row.scene_context&&typeof row.scene_context==='object'?row.scene_context:{},discovery=row.discovery_history&&typeof row.discovery_history==='object'?row.discovery_history:{},researchFrontier=row.research_frontier||'';
 const readerNarrative=row.reader_narrative||row.project_reader_narrative||'',readerResonance=row.reader_resonance||'';
 const readerScene=row.reader_scene&&typeof row.reader_scene==='object'?row.reader_scene:{};
 const readerSequence=row.reader_sequence&&typeof row.reader_sequence==='object'?row.reader_sequence:{};
 const refs=asArray(row.biblical_refs).filter(Boolean),refsHtml=refs.length?`<div class="scripture-ref-list" aria-label="Bible references">${refs.map(ref=>`<button class="scripture-ref-button" type="button" data-scripture-ref="${esc(ref)}">${esc(ref)}</button>`).join('')}</div>`:'';
 const sourceStatus=exact.length?(row.discovery_mode==='public-occurrence'?'public wording':'source-near wording'):'archive synthesis';
 const thesis=compactSummary(readerResonance||argument.why_it_matters||argument.why_dense||row.project_development||why);
 const sourceHtml=`${row.source_direction?`<section class="context-card full"><h4>Timeline / source direction</h4><p>${esc(row.source_direction)}</p></section>`:''}${sceneContext.summary||sceneContext.lead_up||sceneContext.after?`<section class="context-card full"><h4>Scene around the event</h4>${sceneContext.summary?`<p>${esc(sceneContext.summary)}</p>`:''}${sceneContext.lead_up?`<p><strong>Lead-up:</strong> ${esc(sceneContext.lead_up)}</p>`:''}${sceneContext.after?`<p><strong>After:</strong> ${esc(sceneContext.after)}</p>`:''}</section>`:''}${Object.keys(discovery).length?`<section class="context-card full"><h4>Discovery history</h4>${discovery.project_anchor_date?`<p><strong>Event/project anchor:</strong> ${esc(discovery.project_anchor_date)}</p>`:''}${discovery.first_formal_archive_date?`<p><strong>Formal archive comparison:</strong> ${esc(discovery.first_formal_archive_date)}</p>`:''}${discovery.scripture_explicit_at_time?`<p><strong>Scripture at the time:</strong> ${esc(discovery.scripture_explicit_at_time)}</p>`:''}</section>`:''}${researchFrontier?`<section class="context-card full research-gap"><h4>Still worth recovering</h4><p>${esc(researchFrontier)}</p></section>`:''}${evidenceHtml}`;
 const provenanceHtml=`${row.provenance?`<section class="context-card full"><h4>Provenance</h4><p>${esc(row.provenance)}</p></section>`:''}${owners?`<section class="context-card full"><h4>Canonical owners</h4><div class="owner-links">${owners}</div></section>`:''}`;
 const relatedHtml=related.length?related.map(item=>`<button class="related-button" type="button" data-related-id="${esc(item.row.id)}"><span>${esc(item.row.title)}</span><span>${esc(item.row.date||'undated')}</span></button>`).join(''):'<p class="no-fragment">No close neighbours survive the current filter state.</p>';
 const projectSource=exact.length?`<div class="source-voice-card project-voice"><div class="voice-label">Tim / Son source</div>${row.wording_status?`<p class="wording-status">${esc(row.wording_status)}</p>`:''}${exact.slice(0,3).map(q=>`<blockquote class="project-quote">${esc(q)}<cite>${esc(row.discovery_mode||row.evidence_kind||'project-side wording')}</cite></blockquote>`).join('')}</div>`:`<div class="source-voice-card project-voice source-gap"><div class="voice-label">Tim / Son source</div><p>No direct/public/recovered wording is attached to this relation yet. Treat this side as archive synthesis until a closer source is recovered.</p></div>`;
 const bibleSource=`<div class="source-voice-card bible-voice"><div class="voice-label">Bible source</div>${refsHtml}${scriptureHTML(row,fragmentMap)}${scriptureContextItems.length?`<details class="scripture-context"><summary>Passage context</summary>${scriptureContextItems.map(item=>`<p>${esc(item)}</p>`).join('')}</details>`:''}</div>`;
 const sceneParts=[
  ['opening','At that time'],
  ['movement','And it came to pass'],
  ['speech','And the words were'],
  ['response','And those present / what followed'],
  ['turn','And from there'],
  ['scripture_bridge','Under the biblical light']
 ].filter(([key])=>readerScene[key]);
 const sceneHtml=sceneParts.length?`<section class="chronicle-scene"><div class="chronicle-label">The scene <span>source-grounded narrative reconstruction</span></div>${sceneParts.map(([key,label])=>key==='speech'?`<div class="chronicle-beat is-speech"><span>${esc(label)}</span><blockquote>${esc(readerScene[key])}</blockquote></div>`:`<div class="chronicle-beat ${key==='scripture_bridge'?'is-bridge':''}"><span>${esc(label)}</span><p>${esc(readerScene[key])}</p></div>`).join('')}</section>`:'';
 const continuousSequenceSteps=asArray(readerSequence.steps).filter(Boolean);
 const continuousSequenceHtml=continuousSequenceSteps.length?`<section class="continuous-sequence"><div class="continuous-sequence-head"><div><span class="eyebrow">Continuous reading</span><h3>${esc(readerSequence.title||'Scene-led sequence')}</h3></div>${readerSequence.intro?`<p>${esc(readerSequence.intro)}</p>`:''}</div><div class="continuous-sequence-flow">${continuousSequenceSteps.map((step,index)=>`<article class="continuous-step type-${esc(step.source_type||'note')}"><div class="continuous-step-index">${index+1}</div><div class="continuous-step-body"><div class="continuous-step-source">${esc(step.source_label||humanize(step.source_type||'note'))}</div><h4>${esc(step.heading||'Sequence step')}</h4>${step.text?`<p>${esc(step.text)}</p>`:''}${step.quote?`<blockquote>${esc(step.quote)}</blockquote>`:''}${step.ref?`<button class="scripture-ref-button sequence-ref" type="button" data-scripture-ref="${esc(step.ref)}">${esc(step.ref)}</button>`:''}</div></article>`).join('')}</div>${readerSequence.conclusion?`<div class="continuous-sequence-conclusion"><strong>Reading result</strong><p>${esc(readerSequence.conclusion)}</p></div>`:''}</section>`:'';
 const reverentHtml=readerNarrative?`<section class="spudlight-reading"><div class="spudlight-label">Spudlight reading <span>elevated project reflection · not source wording</span></div><p>${esc(readerNarrative)}</p></section>`:'';
 const storyHtml=`<div class="story-pair"><section><h3>Archive grounding</h3><p class="project-anchor">${esc(projectContext)}</p>${sceneDetail?`<p class="scene-detail">${esc(sceneDetail)}</p>`:''}</section><section><h3>What it later becomes</h3><p>${esc(laterMeaning||'No later-development note is attached yet.')}</p></section></div>`;
 const sequenceHtml=`<div class="parallel comparison-sequences"><section class="side project-side"><h3>Tim / Son sequence</h3>${projectSequence.length?`<ol class="comparison-sequence">${projectSequence.map(step=>`<li>${esc(step)}</li>`).join('')}</ol>`:'<p class="no-fragment">No ordered project sequence is attached yet.</p>'}</section><section class="side scripture"><h3>Bible sequence</h3>${biblicalSequence.length?`<ol class="comparison-sequence">${biblicalSequence.map(step=>`<li>${esc(step)}</li>`).join('')}</ol>`:'<p class="no-fragment">No ordered biblical sequence is attached yet.</p>'}</section></div>`;
 const contactHtml=correspondences.length?`<section class="contact-points"><h3>Points of contact</h3><div class="contact-grid">${correspondences.map(item=>`<span>${esc(item)}</span>`).join('')}</div></section>`:'';
 const maximumHtml=maximumClaim?`<div class="maximum-claim"><strong>How far this comparison can go</strong><p>${esc(maximumClaim)}</p></div>`:'';
 const technicalHtml=`<div class="technical-grid"><div><span>Actor</span><strong>${esc(row.actor||'project')}</strong></div><div><span>Evidence</span><strong>${esc(row.evidence_kind||'canonical relation')}</strong></div><div><span>Discovery</span><strong>${esc(humanize(row.discovery_mode||'unspecified'))}</strong></div><div><span>Relation class</span><strong>${esc(humanize(row.relation_class||row.classification||'comparison'))}</strong></div>${operators.length?`<div class="wide"><span>Operators</span><strong>${esc(operators.join(' · '))}</strong></div>`:''}${mechanisms.length?`<div class="wide"><span>Mechanisms</span><strong>${esc(mechanisms.map(humanize).join(' · '))}</strong></div>`:''}<div class="wide"><span>Relation ID</span><code>${esc(row.id)}</code></div></div>`;
 return `<article class="relation" data-relation-id="${esc(row.id)}"><header class="relation-head"><div><div class="relation-kicker">Tim / Son ↔ Bible</div><h2 class="relation-title">${esc(row.title)}</h2>${thesis?`<p class="relation-thesis">${esc(thesis)}</p>`:''}<div class="relation-meta primary-meta"><span class="chip date-chip">${esc(row.date||'undated')}</span><span class="chip ${exact.length?'source-chip':'synthesis-chip'}">${esc(sourceStatus)}</span><span class="chip strength" title="Archive comparison strength; not a truth score">comparison strength ${esc(row.strength||'?')}/5</span></div></div></header><div class="reading-rail" aria-label="How to read this comparison"><span>1 · scene</span><span>2 · sources</span><span>3 · movement</span><span>4 · parallel</span><span>5 · limits</span></div>${sceneHtml}<section class="source-pair">${projectSource}${bibleSource}</section>${continuousSequenceHtml}${reverentHtml}${storyHtml}${sequenceHtml}${contactHtml}<div class="interpretation-pair"><section class="why"><h3>Why these connect</h3><p>${esc(why)}</p></section>${maximumHtml}</div>${mismatch?`<div class="boundary-callout"><strong>Where the comparison breaks</strong><p>${esc(mismatch)}</p></div>`:''}<div class="relation-details"><details><summary>Evidence, chronology & open gaps</summary><div class="detail-body context-grid">${sourceHtml}</div></details><details><summary>Technical detail & provenance</summary><div class="detail-body">${technicalHtml}<div class="context-grid provenance-grid">${provenanceHtml}</div></div></details><details><summary>Related comparisons</summary><div class="detail-body related-list">${relatedHtml}</div></details></div></article>`;
}

async function init(){
 const activeEl=$('active-relation'),staticEl=$('relations');
 try{
  const [field,atlas,fragmentData,attestationData,reverseData,occurrenceData,timelineData]=await Promise.all([safeJSON(PATHS.field),safeJSON(PATHS.atlas),safeJSON(PATHS.fragments),safeJSON(PATHS.attestations),safeJSON(PATHS.reverse),safeJSON(PATHS.occurrences),safeJSON(PATHS.timeline)]);
  if(!field||!fragmentData)throw new Error('canonical Bible relation field or passage fragments unavailable');
  const fieldRows=asArray(field.relations).map(normalizeFieldRow),atlasRows=[...asArray(atlas&&atlas.overlaps).map(item=>normalizeOverlap(item,atlas.updated)),...asArray(atlas&&atlas.meta_arcs).map(item=>normalizeMetaArc(item,atlas.updated))],rowMap=new Map();[...fieldRows,...atlasRows].forEach(row=>{if(row&&row.id&&!rowMap.has(row.id))rowMap.set(row.id,row)});
  const rows=[...rowMap.values()],fragmentMap=fragmentIndex(fragmentData),occurrences=asArray(occurrenceData&&occurrenceData.occurrences),attestations=asArray(attestationData&&attestationData.entries),reversals=asArray(reverseData&&reverseData.events),timelineEvents=asArray(timelineData&&timelineData.events),evidence={occurrenceById:new Map(occurrences.map(item=>[item.id,item])),occurrenceByDate:groupByDate(occurrences,item=>item.date||item.timestamp),attestationByDate:groupByDate(attestations,item=>item.date||item.datetime_utc),reverseByDate:groupByDate(reversals,item=>item.date||item.timestamp),eventById:new Map(timelineEvents.map(item=>[item.id,item])),timelineByDate:groupByDate(timelineEvents,item=>item.date||item.timestamp)};
  const params=new URLSearchParams(location.search),legacyView=params.get('view'),initialFocus=params.get('focus')||(legacyView&&VIEW_DEFS[legacyView]?`view:${legacyView}`:'view:core');
  const state={focus:initialFocus,query:params.get('q')||'',operator:'',actor:'',evidence:'',mode:'',klass:'',book:'',minStrength:0,fromYear:0,toYear:0,exactOnly:false,order:['story','asc','desc','strength','bible'].includes(params.get('order'))?params.get('order'):'story',activeId:params.get('id')||CORE_RELATION_ORDER[0]};
  const populate=(id,values,label=x=>x)=>{const el=$(id);if(!el)return;unique(values).filter(Boolean).sort().forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=label(value);el.appendChild(option)})};
  populate('operator',rows.flatMap(row=>asArray(row.operators)));populate('actor',rows.map(row=>row.actor));populate('evidence-kind',rows.map(row=>row.evidence_kind));populate('discovery-mode',rows.map(row=>row.discovery_mode),x=>String(x).replaceAll('-',' '));populate('relation-class',rows.map(row=>row.relation_class),x=>String(x).replaceAll('-',' '));populate('bible-book',rows.flatMap(row=>asArray(row.biblical_refs).map(bookFromRef)));$('minimum-strength').innerHTML='<option value="0">Any strength</option>'+[1,2,3,4,5].map(n=>`<option value="${n}">${n}+</option>`).join('');
  $('focus-select').value=[...$('focus-select').options].some(option=>option.value===state.focus)?state.focus:'view:core';state.focus=$('focus-select').value;$('order-select').value=state.order;$('search').value=state.query;

  const filteredRows=()=>rows.filter(row=>{if(!matchesFocus(row,state.focus))return false;if(state.operator&&!asArray(row.operators).includes(state.operator))return false;if(state.actor&&row.actor!==state.actor)return false;if(state.evidence&&row.evidence_kind!==state.evidence)return false;if(state.mode&&row.discovery_mode!==state.mode)return false;if(state.klass&&row.relation_class!==state.klass)return false;if(state.book&&!asArray(row.biblical_refs).some(ref=>bookFromRef(ref)===state.book))return false;if(Number(row.strength||0)<state.minStrength)return false;const year=firstYear(row.date);if(state.fromYear&&year&&year<state.fromYear)return false;if(state.toYear&&year&&year>state.toYear)return false;if(state.exactOnly&&!exactAvailable(row,evidence))return false;if(state.query){const terms=state.query.toLowerCase().split(/\s+/).filter(Boolean),hay=rowText(row);if(!terms.every(term=>hay.includes(term)))return false}return true});
  const orderedRows=()=>{const filtered=filteredRows();if(state.order==='story')return [...filtered].sort((a,b)=>(CORE_RELATION_RANK.get(a.id)??9999)-(CORE_RELATION_RANK.get(b.id)??9999)||(firstYear(a.date)??9999)-(firstYear(b.date)??9999));if(state.order==='strength')return [...filtered].sort((a,b)=>(Number(b.strength)||0)-(Number(a.strength)||0)||(firstYear(a.date)??9999)-(firstYear(b.date)??9999));if(state.order==='bible')return [...filtered].sort((a,b)=>bibleOrderKey(a)-bibleOrderKey(b)||(firstYear(a.date)??9999)-(firstYear(b.date)??9999));return [...filtered].sort((a,b)=>{const ay=firstYear(a.date)??9999,by=firstYear(b.date)??9999;return state.order==='desc'?by-ay:ay-by})};
  const filterCount=()=>[state.operator,state.actor,state.evidence,state.mode,state.klass,state.book,state.minStrength,state.fromYear,state.toYear,state.exactOnly].filter(Boolean).length;
  const ensureActive=sequence=>{if(!sequence.length){state.activeId='';return -1}let index=sequence.findIndex(row=>row.id===state.activeId);if(index<0){index=0;state.activeId=sequence[0].id}return index};
  const sequenceLabel=()=>({story:'core story order',asc:'oldest → newest',desc:'newest → oldest',strength:'strongest first',bible:'Genesis → Revelation'})[state.order]||state.order;

  function syncUrlState(){const url=new URL(location.href);url.searchParams.set('focus',state.focus);url.searchParams.set('order',state.order);if(state.activeId)url.searchParams.set('id',state.activeId);else url.searchParams.delete('id');if(state.query)url.searchParams.set('q',state.query);else url.searchParams.delete('q');url.searchParams.delete('view');history.replaceState(null,'',url)}
  function renderResultsList(sequence,index){$('results-list').innerHTML=sequence.length?sequence.map((row,i)=>{const sourced=exactAvailable(row,evidence),hasScene=Boolean(row.reader_scene&&Object.keys(row.reader_scene).length),hasSequence=Boolean(row.reader_sequence&&asArray(row.reader_sequence.steps).length);const argument=row.relation_argument&&typeof row.relation_argument==='object'?row.relation_argument:{};const preview=compactSummary(row.reader_resonance||row.reader_scene?.opening||argument.why_it_matters||argument.why_dense||row.project_development||row.project_context||row.project_anchor,145);return `<button type="button" class="result-item${i===index?' is-active':''}" data-result-id="${esc(row.id)}"><span class="result-index">${String(i+1).padStart(2,'0')}</span><span class="result-main"><span class="result-title">${esc(row.title)}</span>${preview?`<span class="result-preview">${esc(preview)}</span>`:''}<span class="result-tags">${hasScene?'<span>scene</span>':''}${hasSequence?'<span>sequence</span>':''}</span></span><span class="result-meta"><span class="result-quality ${sourced?'is-sourced':'is-synthesis'}">${sourced?'source':'synthesis'}</span><span class="result-date">${esc(row.date||'')}</span></span></button>`}).join(''):'<div class="empty">No results in this sequence.</div>'}
  function render(){const sequence=orderedRows(),index=ensureActive(sequence),row=index>=0?sequence[index]:null;$('active-view').textContent=focusLabel(state.focus);$('study-count').textContent=`${sequence.length} matching this focus · ${rows.length} total canonical comparisons`;$('result-count').textContent=String(sequence.length);$('filter-count').textContent=String(filterCount());$('result-position').textContent=sequence.length?`${index+1} / ${sequence.length}`:'0 / 0';$('sequence-label').textContent=sequenceLabel();$('previous-relation').disabled=index<=0;$('next-relation').disabled=index<0||index>=sequence.length-1;activeEl.innerHTML=renderActiveRelation(row,fragmentMap,evidence,sequence);renderResultsList(sequence,index);document.documentElement.classList.add('js-ready');if(staticEl)staticEl.setAttribute('aria-hidden','true');syncUrlState()}
  function selectRelative(delta){const sequence=orderedRows(),index=ensureActive(sequence),next=index+delta;if(next<0||next>=sequence.length)return;state.activeId=sequence[next].id;render()}
  function selectRandom(){const sequence=orderedRows();if(!sequence.length)return;const current=ensureActive(sequence);let next=current;if(sequence.length>1)while(next===current)next=Math.floor(Math.random()*sequence.length);state.activeId=sequence[next].id;render()}
  function resetFilters(){state.operator='';state.actor='';state.evidence='';state.mode='';state.klass='';state.book='';state.minStrength=0;state.fromYear=0;state.toYear=0;state.exactOnly=false;['from-year','to-year'].forEach(id=>$(id).value='');['operator','actor','evidence-kind','discovery-mode','relation-class','bible-book','minimum-strength'].forEach(id=>$(id).selectedIndex=0);$('exact-wording-only').checked=false;state.activeId='';render()}
  function togglePanel(id,buttonId){const panel=$(id);panel.hidden=!panel.hidden;$(buttonId).setAttribute('aria-expanded',String(!panel.hidden))}

  $('focus-select').addEventListener('change',event=>{state.focus=event.target.value;if(state.focus!=='view:core'&&state.order==='story'){state.order='asc';$('order-select').value='asc'}else if(state.focus==='view:core'&&state.order==='asc'){state.order='story';$('order-select').value='story'}state.activeId='';render()});$('order-select').addEventListener('change',event=>{state.order=event.target.value;render()});$('search').addEventListener('input',event=>{state.query=event.target.value.trim();state.activeId='';render()});$('clear-search').addEventListener('click',()=>{$('search').value='';state.query='';state.activeId='';render();$('search').focus()});
  $('operator').addEventListener('change',event=>{state.operator=event.target.value;state.activeId='';render()});$('actor').addEventListener('change',event=>{state.actor=event.target.value;state.activeId='';render()});$('evidence-kind').addEventListener('change',event=>{state.evidence=event.target.value;state.activeId='';render()});$('discovery-mode').addEventListener('change',event=>{state.mode=event.target.value;state.activeId='';render()});$('relation-class').addEventListener('change',event=>{state.klass=event.target.value;state.activeId='';render()});$('bible-book').addEventListener('change',event=>{state.book=event.target.value;state.activeId='';render()});$('minimum-strength').addEventListener('change',event=>{state.minStrength=Number(event.target.value)||0;state.activeId='';render()});$('from-year').addEventListener('input',event=>{state.fromYear=Number(event.target.value)||0;state.activeId='';render()});$('to-year').addEventListener('input',event=>{state.toYear=Number(event.target.value)||0;state.activeId='';render()});$('exact-wording-only').addEventListener('change',event=>{state.exactOnly=event.target.checked;state.activeId='';render()});
  $('reset-filters').addEventListener('click',resetFilters);$('filter-toggle').addEventListener('click',()=>togglePanel('bible-filters','filter-toggle'));$('results-toggle').addEventListener('click',()=>togglePanel('results-panel','results-toggle'));$('previous-relation').addEventListener('click',()=>selectRelative(-1));$('next-relation').addEventListener('click',()=>selectRelative(1));$('roll-relation').addEventListener('click',selectRandom);
  $('results-list').addEventListener('click',event=>{const button=event.target.closest('[data-result-id]');if(!button)return;state.activeId=button.dataset.resultId;render()});activeEl.addEventListener('click',event=>{const scriptureButton=event.target.closest('[data-scripture-ref]');if(scriptureButton){window.BibleScriptureReader?.openReference(scriptureButton.dataset.scriptureRef);return}const button=event.target.closest('[data-related-id]');if(!button)return;state.activeId=button.dataset.relatedId;render()});
  document.addEventListener('keydown',event=>{const tag=document.activeElement?.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag))return;if(event.key==='ArrowLeft'){event.preventDefault();selectRelative(-1)}else if(event.key==='ArrowRight'){event.preventDefault();selectRelative(1)}else if(event.key==='/'){event.preventDefault();$('search').focus()}else if(event.key.toLowerCase()==='r'){event.preventDefault();selectRandom()}});
  render();
 }catch(error){console.error(error);activeEl.innerHTML='<div class="empty load-error">The comparison engine could not load its canonical data. The compact static index remains available below.</div>'}
}

document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();