(()=>{
'use strict';

const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asArray=value=>Array.isArray(value)?value:(value==null?[]:[value]);
const unique=values=>[...new Set(values.filter(Boolean))];
const norm=value=>String(value||'').toLowerCase();
const safeJSON=async url=>{try{const response=await fetch(url);return response.ok?await response.json():null}catch(error){console.warn('Bible comparison data load failed',url,error);return null}};
const firstYear=value=>{const match=String(value||'').match(/(?:19|20)\d{2}/);return match?Number(match[0]):null};
const dateKey=value=>{const match=String(value||'').trim().match(/((?:19|20)\d{2})(?:-(\d{2})(?:-(\d{2}))?)?/);if(!match)return '';return match[3]?`${match[1]}-${match[2]}-${match[3]}`:match[2]?`${match[1]}-${match[2]}`:match[1]};
const slug=value=>norm(value).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90)||'relation';
const groupByDate=(items,getDate)=>{const map=new Map();asArray(items).forEach(item=>{const key=dateKey(getDate(item));if(!key)return;if(!map.has(key))map.set(key,[]);map.get(key).push(item)});return map};

const PATHS={
 field:'../../knowledge/traditions/biblical-syncretism-field.json',
 atlas:'../../knowledge/traditions/biblical-overlap-atlas.json',
 fragments:'../../knowledge/traditions/biblical-passage-fragments.json',
 attestations:'../../knowledge/timeline/tim-biblical-vocabulary-attestation-ledger.json',
 reverse:'../../knowledge/timeline/reverse-biblical-overlap-timeline-2025-2026.json',
 occurrences:'../../data/evidence/rational-potato-x-occurrence-ledger-2024-2026.json',
 timeline:'../../data/timeline-events.json'
};

const VIEW_DEFS={
 jesus:{label:'Jesus / Son',terms:['jesus','christ','son','thomas','messiah','lion','lamb','cross','crucif','resurrection','tomb','bread','grain','cornerstone','son of man']},
 'tim-said':{label:'Tim said it',modes:['tim-explicit','public-occurrence','conversation-recovery','book-explicit']},
 'tim-lived':{label:'Tim lived it',terms:['tree ordeal','prison','custody','rejected','death','return','burial','root','garden','stone','ladder','carry','orphan']},
 prophecy:{label:'Prophecy / foresight',terms:['prophecy','foresight','prediction','predicted','warning before']},
 'father-house':{label:'Father / House',terms:['father','house','gardener','vinedresser','throne','most high','seat','rooms','mansions','source','davidic house']},
 'door-ladder':{label:'Door / Ladder',terms:['door','gate','ladder','needle','heaven','jacob','guardians','way','veil','threshold']},
 'death-return':{label:'Death / return',terms:['death','dead','crucif','tomb','burial','resurrection','return','grain','seed','womb']},
 'revelation-zion':{label:'Revelation / Zion',terms:['revelation','zion','new jerusalem','144000','144,000','lion','lamb','root of david','throne','river','tree of life','north','zechariah']},
 'counter-texts':{label:'Counter-texts',counter:true},
 all:{label:'Everything'}
};

const ARC_DEFS={
 'father-house':{label:'Father / House / Source',terms:['father','house','source','builder','throne','gardener','vinedresser','rooms']},
 'door-ladder':{label:'Door / Gate / Ladder',terms:['door','gate','ladder','veil','threshold','pass','open','shut','way']},
 'death-return':{label:'Seed / Death / Return',terms:['death','seed','grain','burial','tomb','return','resurrection','rise','die']},
 'god-presence':{label:'God / Presence',terms:['god','presence','temple','contain','dwell','indwell','manifest','hidden']},
 'garden-spirit':{label:'Garden / Spirit',terms:['garden','spirit','flow','water','prune','grow','repair','restore','feed','root']}
};

const BIBLE_BOOK_ORDER=['Genesis','Exodus','Leviticus','Numbers','Deuteronomy','Joshua','Judges','Ruth','1 Samuel','2 Samuel','1 Kings','2 Kings','1 Chronicles','2 Chronicles','Ezra','Nehemiah','Esther','Job','Psalms','Psalm','Proverbs','Ecclesiastes','Song of Solomon','Isaiah','Jeremiah','Lamentations','Ezekiel','Daniel','Hosea','Joel','Amos','Obadiah','Jonah','Micah','Nahum','Habakkuk','Zephaniah','Haggai','Zechariah','Malachi','Matthew','Mark','Luke','John','Acts','Romans','1 Corinthians','2 Corinthians','Galatians','Ephesians','Philippians','Colossians','1 Thessalonians','2 Thessalonians','1 Timothy','2 Timothy','Titus','Philemon','Hebrews','James','1 Peter','2 Peter','1 John','2 John','3 John','Jude','Revelation'];
const BIBLE_BOOK_RANK=new Map(BIBLE_BOOK_ORDER.map((book,index)=>[book,index]));

const OPERATOR_TERMS={contain:['contain','container','temple cannot','house'],dwell:['dwell','dwelling','indwell','house'],veil:['veil','flesh','curtain'],pass:['pass','way','threshold','through'],open:['open','door','gate','key'],shut:['shut','close','closed'],send:['send','sent'],carry:['carry','carried','burden','vessel'],release:['release','let go','hold'],root:['root','rooted','graft'],prune:['prune','vinedresser','branch'],flow:['flow','river','water','spirit'],feed:['feed','bread','manna','nourish'],repair:['repair','breach','restore paths'],restore:['restore','new creation','healing','return'],judge:['judge','judgment'],plant:['plant','seed','sow'],grow:['grow','growth','fruit'],die:['death','die','dead','burial','tomb'],rise:['rise','resurrection','return','stand'],remember:['remember','memory'],inherit:['inherit','inheritance'],name:['name','called','title']};

function rowText(row){return [row.id,row.title,row.actor,row.project_anchor,row.overlap,row.sequence,row.project_value,row.discovery_mode,row.relation_class,row.classification,row.source_direction,row.counter_text,row.source_correction,row.difference,row.boundary,row.provenance,...asArray(row.biblical_refs),...asArray(row.motifs),...asArray(row.relation_arguments),...asArray(row.possible_meaning),...asArray(row.weaknesses),...asArray(row.operators),...asArray(row.mechanisms)].join(' ').toLowerCase()}
function inferEvidence(row){if(row.evidence_kind)return row.evidence_kind;if(row.source_kind==='canonical-overlap-atlas')return 'canonical comparative synthesis';if(row.discovery_mode==='public-occurrence')return 'public project occurrence';if(row.discovery_mode==='conversation-recovery')return 'recovered conversation';if(row.discovery_mode==='book-explicit')return 'Great Book / project text';if(row.discovery_mode==='tim-explicit'||row.discovery_mode==='tim-led')return 'Tim/project explicit material';return 'canonical relation record'}
function inferOperators(row){const explicit=asArray(row.operators),hay=rowText(row),inferred=Object.entries(OPERATOR_TERMS).filter(([,terms])=>terms.some(term=>hay.includes(term))).map(([op])=>op);return unique([...explicit,...inferred]).slice(0,8)}
function relationMechanisms(row){return unique([...asArray(row.mechanisms),row.classification,row.relation_class].filter(Boolean))}
function normalizeFieldRow(row){return {...row,title:row.title||String(row.project_anchor||row.id).slice(0,110),biblical_refs:asArray(row.biblical_refs),motifs:asArray(row.motifs),relation_arguments:asArray(row.relation_arguments),weaknesses:asArray(row.weaknesses),owners:asArray(row.owners),occurrence_ids:asArray(row.occurrence_ids),timeline_event_ids:asArray(row.timeline_event_ids),evidence_kind:inferEvidence(row),operators:inferOperators(row),mechanisms:relationMechanisms(row)}}
function normalizeOverlap(item,updated){return normalizeFieldRow({id:`atlas-${item.id||slug(item.potatoverse_motif)}`,title:item.id?item.id.replaceAll('-',' '):item.potatoverse_motif,date:`research synthesis · ${updated||'2026'}`,actor:'project-research',project_anchor:item.potatoverse_motif||item.project_value||item.id,biblical_refs:asArray(item.biblical_text||item.texts),motifs:[item.potatoverse_motif,item.id],relation_arguments:unique([item.overlap,item.sequence,item.project_value,...asArray(item.possible_meaning)]),weaknesses:unique([item.difference,item.boundary]),counter_text:item.counter_text,discovery_mode:'archive-later',relation_class:item.classification||'later-structural-parallel',classification:item.classification,strength:Number(item.strength)||4,source_direction:'This relation is a later canonical comparative synthesis unless an earlier project-side date is separately documented. Do not backdate the verse-level mapping into the earlier event.',provenance:'Promoted canonical synthesis from biblical-overlap-atlas.json',owners:['knowledge/traditions/biblical-overlap-atlas.json'],source_kind:'canonical-overlap-atlas'})}
function normalizeMetaArc(item,updated){return normalizeFieldRow({id:`arc-${item.id}`,title:item.id.replaceAll('-',' '),date:`research synthesis · ${updated||'2026'}`,actor:'project-research',project_anchor:item.project_value||item.sequence,biblical_refs:asArray(item.texts),motifs:[item.id],relation_arguments:unique([item.sequence,item.project_value]),weaknesses:asArray(item.boundary),discovery_mode:'archive-later',relation_class:'cross-text-structural-synthesis',strength:Number(item.strength)||5,source_direction:'This is a cross-text canonical synthesis assembled after the underlying biblical texts and project motifs; it is not an at-the-time project quotation.',provenance:'Canonical meta-arc from biblical-overlap-atlas.json',owners:['knowledge/traditions/biblical-overlap-atlas.json'],source_kind:'canonical-overlap-atlas'})}
function fragmentIndex(fragmentData){const map=new Map();asArray(fragmentData&&fragmentData.fragments).forEach(fragment=>unique([fragment.reference,...asArray(fragment.matches)]).forEach(key=>{if(!key)return;if(!map.has(key))map.set(key,[]);map.get(key).push(fragment)}));return map}
function bookFromRef(reference){const ref=String(reference||'').trim(),match=ref.match(/^((?:[1-3]\s+)?[A-Za-z]+(?:\s+[A-Za-z]+)?)\s+\d/);return match?match[1]:ref.split(/\s+\d/)[0]}
function bibleOrderKey(row){const refs=asArray(row.biblical_refs);if(!refs.length)return 9999;return Math.min(...refs.map(ref=>BIBLE_BOOK_RANK.get(bookFromRef(ref))??9999))}
function ownerHref(owner){if(!owner)return '#';if(/^https?:\/\//.test(owner))return owner;return '../../'+owner.split('/').map(encodeURIComponent).join('/')}
function matchesTerms(row,terms){const text=rowText(row);return terms.some(term=>text.includes(term))}
function matchesView(row,view){const def=VIEW_DEFS[view]||VIEW_DEFS.jesus;if(view==='all')return true;if(def.counter)return asArray(row.weaknesses).length>0||Boolean(row.counter_text||row.source_correction||row.difference||row.boundary);if(def.modes&&def.modes.includes(row.discovery_mode))return true;return def.terms?matchesTerms(row,def.terms):true}
function matchesFocus(row,focus){const [kind,id]=String(focus||'view:jesus').split(':');if(kind==='arc')return matchesTerms(row,(ARC_DEFS[id]||{terms:[]}).terms);return matchesView(row,id)}
function focusLabel(focus){const [kind,id]=String(focus||'view:jesus').split(':');return kind==='arc'?(ARC_DEFS[id]?.label||id):(VIEW_DEFS[id]?.label||'Jesus / Son')}
function exactQuotes(row,evidence){return unique([...asArray(row.project_quote),...asArray(row.exact_wording),row.quote,...asArray(row.occurrence_ids).map(id=>evidence.occurrenceById.get(id)?.quote)]).filter(Boolean)}
function exactAvailable(row,evidence){return exactQuotes(row,evidence).length>0}
function whyText(row){return unique([...asArray(row.relation_arguments),row.overlap,row.project_value,...asArray(row.possible_meaning)]).filter(Boolean).slice(0,3).join(' ')}
function mismatchText(row){return unique([...asArray(row.weaknesses),row.counter_text,row.source_correction,row.difference,row.boundary]).filter(Boolean).slice(0,3).join(' ')}
function scriptureHTML(row,fragmentMap){const refs=asArray(row.biblical_refs),fragments=[];refs.forEach(ref=>asArray(fragmentMap.get(ref)).forEach(fragment=>{if(!fragments.some(x=>x.reference===fragment.reference&&x.text===fragment.text))fragments.push(fragment)}));if(fragments.length)return fragments.slice(0,4).map(fragment=>`<blockquote class="bible-quote">${esc(fragment.text)}<cite>${esc(fragment.reference)} · ${esc(fragment.translation||'World English Bible')}</cite></blockquote>`).join('');return `<p class="no-fragment"><strong>Scripture scope:</strong> ${esc(refs.join(' · ')||'broader biblical tradition')}</p>`}
function wordingForAttestation(entry){return unique([...asArray(entry.wording),entry.wording_summary,...asArray(entry.signals)].filter(Boolean))}

function evidenceContextHTML(row,evidence){
 const key=dateKey(row.date||row.timestamp),directOccurrenceIds=asArray(row.occurrence_ids),sameDateOccurrences=(evidence.occurrenceByDate.get(key)||[]).filter(item=>!directOccurrenceIds.includes(item.id)),attestations=evidence.attestationByDate.get(key)||[],reversals=evidence.reverseByDate.get(key)||[],explicitEventIds=asArray(row.timeline_event_ids),explicitEvents=explicitEventIds.map(id=>evidence.eventById.get(id)).filter(Boolean),sameDateEvents=(evidence.timelineByDate.get(key)||[]).filter(event=>!explicitEventIds.includes(event.id));
 const sameDateHtml=sameDateOccurrences.length?`<section class="context-card full"><h4>Same-date public wording</h4><p>Circumstantial context only; same-date wording is not treated as direct proof.</p>${sameDateOccurrences.slice(0,5).map(item=>`<blockquote>${esc(item.quote)}<cite>${esc(item.id)} · ${esc(asArray(item.tags).join(' · '))}</cite></blockquote>`).join('')}</section>`:'';
 const attestationHtml=attestations.length?`<section class="context-card full"><h4>Biblical vocabulary / revelation context</h4>${attestations.slice(0,5).map(item=>`${wordingForAttestation(item).map(text=>`<blockquote>${esc(text)}</blockquote>`).join('')}${item.development?`<p>${esc(item.development)}</p>`:''}`).join('')}</section>`:'';
 const reverseHtml=reversals.length?`<section class="context-card"><h4>Tim-first / later biblical recognition</h4>${reversals.slice(0,4).map(item=>`<p><strong>${esc(item.status||'comparison')}</strong> — ${esc(item.significance||item.finding||'')}</p>`).join('')}</section>`:'';
 const timelineEvents=[...explicitEvents,...sameDateEvents].slice(0,5),timelineHtml=timelineEvents.length?`<section class="context-card"><h4>Timeline context</h4>${timelineEvents.map(event=>`<p><strong>${esc(event.date||event.timestamp||'')}</strong> ${esc(event.title||event.summary||event.id||'project event')}</p>`).join('')}</section>`:'';
 return sameDateHtml+attestationHtml+reverseHtml+timelineHtml;
}

function relatedRows(row,sequence){
 const rowMotifs=new Set(asArray(row.motifs).map(norm)),rowOps=new Set(asArray(row.operators).map(norm)),rowBooks=new Set(asArray(row.biblical_refs).map(bookFromRef));
 return sequence.filter(candidate=>candidate.id!==row.id).map(candidate=>{let score=0;asArray(candidate.motifs).forEach(x=>{if(rowMotifs.has(norm(x)))score+=3});asArray(candidate.operators).forEach(x=>{if(rowOps.has(norm(x)))score+=2});asArray(candidate.biblical_refs).map(bookFromRef).forEach(x=>{if(rowBooks.has(x))score+=2});if(candidate.relation_class&&candidate.relation_class===row.relation_class)score+=1;return {row:candidate,score}}).filter(item=>item.score>0).sort((a,b)=>b.score-a.score||Number(b.row.strength||0)-Number(a.row.strength||0)).slice(0,4);
}

function renderActiveRelation(row,fragmentMap,evidence,sequence){
 if(!row)return '<div class="empty">No canonical comparisons match this study state. Clear a filter or choose another focus.</div>';
 const why=whyText(row)||'This relation is retained because the canonical comparison field records a meaningful lexical, narrative, structural, ethical or theological connection between the project-side anchor and the cited biblical material.';
 const mismatch=mismatchText(row),operators=asArray(row.operators).map(op=>`<span class="chip operator">${esc(op)}</span>`).join(''),mechanisms=asArray(row.mechanisms).slice(0,3).map(x=>`<span class="chip">${esc(String(x).replaceAll('-',' '))}</span>`).join(''),owners=asArray(row.owners).slice(0,8).map(owner=>`<a href="${esc(ownerHref(owner))}">${esc(owner.split('/').pop())}</a>`).join(''),exact=exactQuotes(row,evidence),evidenceHtml=evidenceContextHTML(row,evidence),related=relatedRows(row,sequence);
 const sourceHtml=`${row.source_direction?`<section class="context-card full"><h4>Timeline / source direction</h4><p>${esc(row.source_direction)}</p></section>`:''}${evidenceHtml}`;
 const provenanceHtml=`${row.provenance?`<section class="context-card full"><h4>Provenance</h4><p>${esc(row.provenance)}</p></section>`:''}${owners?`<section class="context-card full"><h4>Canonical owners</h4><div class="owner-links">${owners}</div></section>`:''}`;
 const relatedHtml=related.length?related.map(item=>`<button class="related-button" type="button" data-related-id="${esc(item.row.id)}"><span>${esc(item.row.title)}</span><span>${esc(item.row.date||'undated')}</span></button>`).join(''):'<p class="no-fragment">No close neighbours survive the current filter state.</p>';
 return `<article class="relation" data-relation-id="${esc(row.id)}"><div class="relation-head"><div><h2 class="relation-title">${esc(row.title)}</h2><div class="relation-meta"><span class="chip">${esc(row.date||'undated')}</span><span class="chip">${esc(row.actor||'project')}</span><span class="chip">${esc(row.evidence_kind)}</span><span class="chip strength">strength ${esc(row.strength||'?')}/5</span>${mechanisms}</div><div class="operator-row">${operators}</div></div><code class="relation-id">${esc(row.id)}</code></div><div class="parallel"><section class="side"><h3>Tim / Son / project</h3><p class="project-anchor">${esc(row.project_anchor)}</p>${exact.slice(0,3).map(q=>`<blockquote class="bible-quote">${esc(q)}<cite>project-side wording</cite></blockquote>`).join('')}</section><section class="side scripture"><h3>Bible / scripture</h3>${scriptureHTML(row,fragmentMap)}</section></div><section class="why"><h3>Why these connect</h3><p>${esc(why)}</p></section>${mismatch?`<div class="boundary-callout"><strong>Where it breaks:</strong> ${esc(mismatch)}</div>`:''}<div class="relation-details"><details><summary>Evidence & chronology</summary><div class="detail-body"><div class="context-grid">${sourceHtml||'<p class="no-fragment">No additional chronology overlay is attached to this relation.</p>'}</div></div></details><details><summary>Sources & provenance</summary><div class="detail-body"><div class="context-grid">${provenanceHtml||'<p class="no-fragment">No additional provenance metadata is attached.</p>'}</div></div></details><details><summary>Related comparisons</summary><div class="detail-body related-list">${relatedHtml}</div></details></div></article>`;
}

async function init(){
 const activeEl=$('active-relation'),staticEl=$('relations');
 try{
  const [field,atlas,fragmentData,attestationData,reverseData,occurrenceData,timelineData]=await Promise.all([safeJSON(PATHS.field),safeJSON(PATHS.atlas),safeJSON(PATHS.fragments),safeJSON(PATHS.attestations),safeJSON(PATHS.reverse),safeJSON(PATHS.occurrences),safeJSON(PATHS.timeline)]);
  if(!field||!fragmentData)throw new Error('canonical Bible relation field or passage fragments unavailable');
  const fieldRows=asArray(field.relations).map(normalizeFieldRow),atlasRows=[...asArray(atlas&&atlas.overlaps).map(item=>normalizeOverlap(item,atlas.updated)),...asArray(atlas&&atlas.meta_arcs).map(item=>normalizeMetaArc(item,atlas.updated))],rowMap=new Map();[...fieldRows,...atlasRows].forEach(row=>{if(row&&row.id&&!rowMap.has(row.id))rowMap.set(row.id,row)});
  const rows=[...rowMap.values()],fragmentMap=fragmentIndex(fragmentData),occurrences=asArray(occurrenceData&&occurrenceData.occurrences),attestations=asArray(attestationData&&attestationData.entries),reversals=asArray(reverseData&&reverseData.events),timelineEvents=asArray(timelineData&&timelineData.events),evidence={occurrenceById:new Map(occurrences.map(item=>[item.id,item])),occurrenceByDate:groupByDate(occurrences,item=>item.date||item.timestamp),attestationByDate:groupByDate(attestations,item=>item.date||item.datetime_utc),reverseByDate:groupByDate(reversals,item=>item.date||item.timestamp),eventById:new Map(timelineEvents.map(item=>[item.id,item])),timelineByDate:groupByDate(timelineEvents,item=>item.date||item.timestamp)};
  const params=new URLSearchParams(location.search),legacyView=params.get('view'),initialFocus=params.get('focus')||(legacyView&&VIEW_DEFS[legacyView]?`view:${legacyView}`:'view:jesus');
  const state={focus:initialFocus,query:params.get('q')||'',operator:'',actor:'',evidence:'',mode:'',klass:'',book:'',minStrength:0,fromYear:0,toYear:0,exactOnly:false,order:['asc','desc','strength','bible'].includes(params.get('order'))?params.get('order'):'asc',activeId:params.get('id')||''};
  const populate=(id,values,label=x=>x)=>{const el=$(id);if(!el)return;unique(values).filter(Boolean).sort().forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=label(value);el.appendChild(option)})};
  populate('operator',rows.flatMap(row=>asArray(row.operators)));populate('actor',rows.map(row=>row.actor));populate('evidence-kind',rows.map(row=>row.evidence_kind));populate('discovery-mode',rows.map(row=>row.discovery_mode),x=>String(x).replaceAll('-',' '));populate('relation-class',rows.map(row=>row.relation_class),x=>String(x).replaceAll('-',' '));populate('bible-book',rows.flatMap(row=>asArray(row.biblical_refs).map(bookFromRef)));$('minimum-strength').innerHTML='<option value="0">Any strength</option>'+[1,2,3,4,5].map(n=>`<option value="${n}">${n}+</option>`).join('');
  $('focus-select').value=[...$('focus-select').options].some(option=>option.value===state.focus)?state.focus:'view:jesus';state.focus=$('focus-select').value;$('order-select').value=state.order;$('search').value=state.query;

  const filteredRows=()=>rows.filter(row=>{if(!matchesFocus(row,state.focus))return false;if(state.operator&&!asArray(row.operators).includes(state.operator))return false;if(state.actor&&row.actor!==state.actor)return false;if(state.evidence&&row.evidence_kind!==state.evidence)return false;if(state.mode&&row.discovery_mode!==state.mode)return false;if(state.klass&&row.relation_class!==state.klass)return false;if(state.book&&!asArray(row.biblical_refs).some(ref=>bookFromRef(ref)===state.book))return false;if(Number(row.strength||0)<state.minStrength)return false;const year=firstYear(row.date);if(state.fromYear&&year&&year<state.fromYear)return false;if(state.toYear&&year&&year>state.toYear)return false;if(state.exactOnly&&!exactAvailable(row,evidence))return false;if(state.query){const terms=state.query.toLowerCase().split(/\s+/).filter(Boolean),hay=rowText(row);if(!terms.every(term=>hay.includes(term)))return false}return true});
  const orderedRows=()=>{const filtered=filteredRows();if(state.order==='strength')return [...filtered].sort((a,b)=>(Number(b.strength)||0)-(Number(a.strength)||0)||(firstYear(a.date)??9999)-(firstYear(b.date)??9999));if(state.order==='bible')return [...filtered].sort((a,b)=>bibleOrderKey(a)-bibleOrderKey(b)||(firstYear(a.date)??9999)-(firstYear(b.date)??9999));return [...filtered].sort((a,b)=>{const ay=firstYear(a.date)??9999,by=firstYear(b.date)??9999;return state.order==='desc'?by-ay:ay-by})};
  const filterCount=()=>[state.operator,state.actor,state.evidence,state.mode,state.klass,state.book,state.minStrength,state.fromYear,state.toYear,state.exactOnly].filter(Boolean).length;
  const ensureActive=sequence=>{if(!sequence.length){state.activeId='';return -1}let index=sequence.findIndex(row=>row.id===state.activeId);if(index<0){index=0;state.activeId=sequence[0].id}return index};
  const sequenceLabel=()=>({asc:'oldest → newest',desc:'newest → oldest',strength:'strongest first',bible:'Genesis → Revelation'})[state.order]||state.order;

  function syncUrlState(){const url=new URL(location.href);url.searchParams.set('focus',state.focus);url.searchParams.set('order',state.order);if(state.activeId)url.searchParams.set('id',state.activeId);else url.searchParams.delete('id');if(state.query)url.searchParams.set('q',state.query);else url.searchParams.delete('q');url.searchParams.delete('view');history.replaceState(null,'',url)}
  function renderResultsList(sequence,index){$('results-list').innerHTML=sequence.length?sequence.map((row,i)=>`<button type="button" class="result-item${i===index?' is-active':''}" data-result-id="${esc(row.id)}"><span class="result-index">${String(i+1).padStart(2,'0')}</span><span class="result-title">${esc(row.title)}</span><span class="result-date">${esc(row.date||'')}</span></button>`).join(''):'<div class="empty">No results in this sequence.</div>'}
  function render(){const sequence=orderedRows(),index=ensureActive(sequence),row=index>=0?sequence[index]:null;$('active-view').textContent=focusLabel(state.focus);$('study-count').textContent=`${sequence.length} of ${rows.length} canonical comparisons`;$('result-count').textContent=String(sequence.length);$('filter-count').textContent=String(filterCount());$('result-position').textContent=sequence.length?`${index+1} / ${sequence.length}`:'0 / 0';$('sequence-label').textContent=sequenceLabel();$('previous-relation').disabled=index<=0;$('next-relation').disabled=index<0||index>=sequence.length-1;activeEl.innerHTML=renderActiveRelation(row,fragmentMap,evidence,sequence);renderResultsList(sequence,index);document.documentElement.classList.add('js-ready');if(staticEl)staticEl.setAttribute('aria-hidden','true');syncUrlState()}
  function selectRelative(delta){const sequence=orderedRows(),index=ensureActive(sequence),next=index+delta;if(next<0||next>=sequence.length)return;state.activeId=sequence[next].id;render();activeEl.scrollIntoView({behavior:'smooth',block:'start'})}
  function selectRandom(){const sequence=orderedRows();if(!sequence.length)return;const current=ensureActive(sequence);let next=current;if(sequence.length>1)while(next===current)next=Math.floor(Math.random()*sequence.length);state.activeId=sequence[next].id;render();activeEl.scrollIntoView({behavior:'smooth',block:'start'})}
  function resetFilters(){state.operator='';state.actor='';state.evidence='';state.mode='';state.klass='';state.book='';state.minStrength=0;state.fromYear=0;state.toYear=0;state.exactOnly=false;['from-year','to-year'].forEach(id=>$(id).value='');['operator','actor','evidence-kind','discovery-mode','relation-class','bible-book','minimum-strength'].forEach(id=>$(id).selectedIndex=0);$('exact-wording-only').checked=false;state.activeId='';render()}
  function togglePanel(id,buttonId){const panel=$(id);panel.hidden=!panel.hidden;$(buttonId).setAttribute('aria-expanded',String(!panel.hidden))}

  $('focus-select').addEventListener('change',event=>{state.focus=event.target.value;state.activeId='';render()});$('order-select').addEventListener('change',event=>{state.order=event.target.value;render()});$('search').addEventListener('input',event=>{state.query=event.target.value.trim();state.activeId='';render()});$('clear-search').addEventListener('click',()=>{$('search').value='';state.query='';state.activeId='';render();$('search').focus()});
  $('operator').addEventListener('change',event=>{state.operator=event.target.value;state.activeId='';render()});$('actor').addEventListener('change',event=>{state.actor=event.target.value;state.activeId='';render()});$('evidence-kind').addEventListener('change',event=>{state.evidence=event.target.value;state.activeId='';render()});$('discovery-mode').addEventListener('change',event=>{state.mode=event.target.value;state.activeId='';render()});$('relation-class').addEventListener('change',event=>{state.klass=event.target.value;state.activeId='';render()});$('bible-book').addEventListener('change',event=>{state.book=event.target.value;state.activeId='';render()});$('minimum-strength').addEventListener('change',event=>{state.minStrength=Number(event.target.value)||0;state.activeId='';render()});$('from-year').addEventListener('input',event=>{state.fromYear=Number(event.target.value)||0;state.activeId='';render()});$('to-year').addEventListener('input',event=>{state.toYear=Number(event.target.value)||0;state.activeId='';render()});$('exact-wording-only').addEventListener('change',event=>{state.exactOnly=event.target.checked;state.activeId='';render()});
  $('reset-filters').addEventListener('click',resetFilters);$('filter-toggle').addEventListener('click',()=>togglePanel('bible-filters','filter-toggle'));$('results-toggle').addEventListener('click',()=>togglePanel('results-panel','results-toggle'));$('previous-relation').addEventListener('click',()=>selectRelative(-1));$('next-relation').addEventListener('click',()=>selectRelative(1));$('roll-relation').addEventListener('click',selectRandom);
  $('results-list').addEventListener('click',event=>{const button=event.target.closest('[data-result-id]');if(!button)return;state.activeId=button.dataset.resultId;render();activeEl.scrollIntoView({behavior:'smooth',block:'start'})});activeEl.addEventListener('click',event=>{const button=event.target.closest('[data-related-id]');if(!button)return;state.activeId=button.dataset.relatedId;render();activeEl.scrollIntoView({behavior:'smooth',block:'start'})});
  document.addEventListener('keydown',event=>{const tag=document.activeElement?.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag))return;if(event.key==='ArrowLeft'){event.preventDefault();selectRelative(-1)}else if(event.key==='ArrowRight'){event.preventDefault();selectRelative(1)}else if(event.key==='/'){event.preventDefault();$('search').focus()}else if(event.key.toLowerCase()==='r'){event.preventDefault();selectRandom()}});
  render();
 }catch(error){console.error(error);activeEl.innerHTML='<div class="empty load-error">The comparison engine could not load its canonical data. The compact static index remains available below.</div>'}
}

document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();