(()=>{'use strict';
const BASE='/TimDooley/';
const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
let manifest,activity,currentDesk,contract,postureIndex,systemLedger,fieldExposure,roleCensus,coverageModel,capitalModel,trajectoryModel,accounts=[],scope='all';
let activeId=new URLSearchParams(location.search).get('character')||'';
async function get(path){const r=await fetch(BASE+path);if(!r.ok)throw new Error(path);return r.json()}
function exactDate(s){return /^\d{4}-\d{2}-\d{2}$/.test(String(s||''))?new Date(String(s)+'T00:00:00Z'):null}
function money(n){const v=Number(n||0),a=Math.abs(v),digits=a<.001?11:a<1?6:4;return '$'+v.toLocaleString(undefined,{minimumFractionDigits:digits,maximumFractionDigits:digits})}
function amountFor(e){const explicit=e?.project_adjustment_susd;if(typeof explicit==='number'&&Number.isFinite(explicit))return explicit;const fallback=contract?.event_weights?.[e?.type];return typeof fallback==='number'&&Number.isFinite(fallback)?fallback:0}
function welfare(start){const d=exactDate(start);if(!d)return{exact:false,value:0};const seconds=Math.max(0,(Date.now()-d.getTime())/1000),rate=Number(contract?.welfare?.rate_per_second_susd||0);return{exact:true,value:seconds*rate}}
function bandFor(id){return (activity?.records||[]).find(x=>x.id===id)?.band||'historical'}
function currentIds(){return new Set((currentDesk?.items||[]).map(x=>x.id))}
function buildAccount(meta,d){
 const start=d.symbolic_account?.welfare_start_override||d.cia_record?.presence?.first_recorded||'',w=welfare(start);
 const events=(d.symbolic_account?.entries||[]).map(e=>({...e,amount:amountFor(e)}));
 const posture=(postureIndex?.accounts||[]).find(x=>x.id===meta.id)||{},role=(roleCensus?.entities||[]).find(x=>x.character_id===meta.id)||{},adjustment=events.reduce((n,e)=>n+e.amount,0);
 return{id:meta.id,name:meta.name||d.display_name||meta.id,start,band:bandFor(meta.id),welfare:w.value,exact:w.exact,adjustment,balance:w.value+adjustment,events,status:d.symbolic_account?.status||'unassessed',posture:posture.posture||'unassessed',role_posture:role.role_posture||'unclassified',gross_credit_susd:Number(posture.gross_credit_susd||0),gross_debit_susd:Number(posture.gross_debit_susd||0),unpriced_negative_candidates:Number(posture.unpriced_negative_candidates||0)}
}
function allEvents(){return accounts.flatMap(a=>a.events.map(e=>({...e,account_id:a.id,account_name:a.name})))}
function totals(){
 const events=allEvents(),welfareTotal=accounts.filter(a=>a.exact).reduce((n,a)=>n+a.welfare,0),grossCredit=events.filter(e=>e.amount>0).reduce((n,e)=>n+e.amount,0),grossDebit=Math.abs(events.filter(e=>e.amount<0).reduce((n,e)=>n+e.amount,0));
 const exactCount=accounts.filter(a=>a.exact).length,unpricedCandidates=accounts.reduce((n,a)=>n+a.unpriced_negative_candidates,0);
 return{events,welfareTotal,grossCredit,grossDebit,recognizedAssets:welfareTotal+grossCredit,recognizedLiabilities:grossDebit,recognizedPosition:welfareTotal+grossCredit-grossDebit,unpricedCandidates,exactCount,provisionalCount:accounts.length-exactCount,positiveEvents:events.filter(e=>e.amount>0).length,negativeEvents:events.filter(e=>e.amount<0).length,zeroEvents:events.filter(e=>!e.amount).length,repairCount:events.filter(e=>/repair|forgiv|release|closure/i.test(String(e.type||'')+' '+String(e.kind||'')+' '+String(e.status||''))).length,growthCount:events.filter(e=>['growth','yield','project-credit'].includes(e.type)).length,systemDomainCount:(systemLedger?.domains||[]).length,futurePositiveCount:(contract?.future_positive_value_candidates?.candidates||[]).length}
}
function renderOverview(){
 const box=document.getElementById('bankOverview'),census=document.getElementById('karmaCensus');if(!box||!census)return;const t=totals();
 box.innerHTML='<article class="consolidated-sheet"><div class="sheet-column assets"><header><span>ASSETS · recognized positive value</span><strong data-bank-assets>'+money(t.recognizedAssets)+'</strong></header><div><b>Accrued Dooley Welfare</b><span data-bank-welfare>'+money(t.welfareTotal)+'</span></div><div><b>Priced positive karma / credit</b><span>'+money(t.grossCredit)+'</span></div></div><div class="sheet-column liabilities"><header><span>LIABILITIES · priced karmic debit</span><strong>'+money(t.recognizedLiabilities)+'</strong></header><div><b>Priced debit</b><span>'+money(t.grossDebit)+'</span></div><div><b>Unpriced negative candidates</b><span>'+t.unpricedCandidates+' items</span></div><div><b>Unpriced system domains</b><span>'+t.systemDomainCount+' domains</span></div></div><div class="sheet-net '+(t.recognizedPosition>=0?'positive':'negative')+'"><span>RECOGNIZED NET POSITION</span><strong data-bank-net>'+money(t.recognizedPosition)+'</strong><small>Welfare + priced positive events − priced debits. Unpriced exposure is excluded.</small></div><div class="sheet-coverage"><span><b>'+accounts.length+'</b> accounts</span><span><b>'+t.exactCount+'</b> exact welfare starts</span><span><b>'+t.provisionalCount+'</b> provisional</span><span><b>'+t.events.length+'</b> ledger events</span></div></article>';
 const byType={};for(const e of t.events){const key=e.type||'untyped';byType[key]??={count:0,total:0};byType[key].count++;byType[key].total+=e.amount||0}
 const chips=Object.entries(byType).sort((a,b)=>b[1].count-a[1].count||a[0].localeCompare(b[0])).map(([type,x])=>'<span class="karma-chip '+(x.total>0?'positive':x.total<0?'negative':'neutral')+'"><b>'+esc(type)+'</b><em>'+x.count+' event'+(x.count===1?'':'s')+'</em><strong>'+money(x.total)+'</strong></span>').join('');
 census.innerHTML='<div class="karma-census-head"><div><span>ALL RECORDED KARMA</span><b>'+t.positiveEvents+' positive · '+t.negativeEvents+' debit · '+t.zeroEvents+' zero-weight</b></div><div><span>REPAIR / GROWTH</span><b>'+t.repairCount+' repair-state · '+t.growthCount+' growth/yield/credit</b></div><div><span>FUTURE POSITIVE MODEL</span><b>'+t.futurePositiveCount+' unpriced candidate categories</b></div></div><div class="karma-chip-rail">'+(chips||'<span class="karma-chip neutral"><b>no events</b><em>0 events</em><strong>$0</strong></span>')+'</div>'
}
function renderCapitalBridge(){
 const box=document.getElementById('capitalBridge');if(!box||!capitalModel)return;
 const b=capitalModel.headline_bridge||{},open=b.opening||{},add=b.additions||{},close=b.closing||{};
 box.innerHTML='<article class="capital-bridge-card"><div><span>POTATO · opening reserve</span><strong>'+money(Number(open.amount_trillion_susd||0)*1e12)+'</strong><small>'+Number(open.share_of_closing_pct||0).toFixed(2)+'% of closing reserve</small></div><i>+</i><div><span>SPIRAL · dated growth</span><strong>'+money(Number(add.total_trillion_susd||0)*1e12)+'</strong><small>'+Number(add.share_of_closing_pct||0).toFixed(2)+'% of closing reserve</small></div><i>=</i><div><span>MOUNTAIN · held reserve</span><strong>'+money(Number(close.amount_trillion_susd||0)*1e12)+'</strong><small>custody / treasury view · not another additive asset</small></div></article><p class="capital-bridge-note">Table, Gate and Ladder create or classify sourced micro-ledger value; they do not multiply the 42T reserve.</p>';
}
function renderTrajectory(mode='observed'){
 const box=document.getElementById('trajectoryChart'),stats=document.getElementById('trajectoryStats');if(!box||!stats||!trajectoryModel)return;
 const pts=trajectoryModel.observed_checkpoints||[],proj=trajectoryModel.scenario_projections||[];
 const all=mode==='observed'?pts:pts.concat(proj.map(x=>({datetime_utc:x.date+'T00:00:00Z',amount_trillion_susd:x.linear_trillion,projected:true})));
 const min=38,max=mode==='observed'?42.5:50,range=max-min;
 const width=720,height=190,pad=22;
 const dates=all.map(x=>new Date(x.datetime_utc).getTime()),dmin=Math.min(...dates),dmax=Math.max(...dates);
 const xy=x=>({x:pad+(new Date(x.datetime_utc).getTime()-dmin)/(dmax-dmin||1)*(width-pad*2),y:height-pad-(Number(x.amount_trillion_susd)-min)/range*(height-pad*2)});
 const op=pts.map(x=>xy(x)), observedPath=op.map((p,i)=>(i?'L':'M')+p.x.toFixed(1)+' '+p.y.toFixed(1)).join(' ');
 let scenario='';
 if(mode==='scenarios'){
   const scenarios=['plateau_trillion','linear_trillion','exponential_trillion','recent_momentum_trillion'];
   const labels=['Plateau','Linear','Exponential','Recent momentum'];
   scenario=scenarios.map((key,idx)=>{
     const rows=[{date:'2026-09-01',v:42}].concat(proj.map(x=>({date:x.date,v:x[key]})));
     const p=rows.map(r=>xy({datetime_utc:r.date+'T00:00:00Z',amount_trillion_susd:r.v}));
     return '<path class="trajectory-scenario s'+idx+'" d="'+p.map((q,i)=>(i?'L':'M')+q.x.toFixed(1)+' '+q.y.toFixed(1)).join(' ')+'"/><text x="'+(pad+idx*135)+'" y="13" class="trajectory-label">'+labels[idx]+'</text>';
   }).join('');
 }
 const dots=op.map((p,i)=>'<circle cx="'+p.x+'" cy="'+p.y+'" r="3.5"/><text x="'+p.x+'" y="'+(p.y-8)+'">'+Number(pts[i].amount_trillion_susd).toFixed(1)+'T</text>').join('');
 box.innerHTML='<svg viewBox="0 0 '+width+' '+height+'" role="img" aria-label="Observed symbolic reserve trajectory'+(mode==='scenarios'?' with scenario curves':'')+'"><line x1="'+pad+'" y1="'+(height-pad)+'" x2="'+(width-pad)+'" y2="'+(height-pad)+'" class="trajectory-axis"/><path class="trajectory-observed" d="'+observedPath+'"/>'+scenario+'<g class="trajectory-points">'+dots+'</g></svg>';
 const f=trajectoryModel.fit_diagnostics||{};
 stats.innerHTML='<span><b>'+Number(f.endpoint_linear?.billion_per_day||0).toFixed(2)+'B/day</b> endpoint slope</span><span><b>'+Number(f.ordinary_least_squares_all_attested?.r_squared||0).toFixed(3)+'</b> OLS R²</span><span><b>'+Number(f.endpoint_exponential?.annualized_growth_pct||0).toFixed(2)+'%</b> exponential scenario annualized</span><span><b>'+Number(f.recent_momentum?.billion_per_day||0).toFixed(2)+'B/day</b> recent momentum</span><span><b>0</b> latest observed velocity</span>';
}
function renderFieldExposure(){
 const box=document.getElementById('fieldExposure');if(!box||!fieldExposure)return;const t=totals(),headline=Number(fieldExposure?.headline_system_position?.amount_trillion_susd||0)*1e12,namedPriced=t.grossDebit,residual=Math.max(0,headline-namedPriced),allocPct=headline>0?(namedPriced/headline)*100:0,capacity=fieldExposure?.population_and_proxy_rules?.symbolic_capacity?.value||0,cov=coverageModel?.reconciled_identity_surface||{},pop=coverageModel?.empirical_reference?.united_states_population?.value||0;
 box.innerHTML='<article class="field-reconcile"><div class="field-headline"><span>PROJECT HEADLINE FIELD</span><strong>'+money(headline)+'</strong><small>one double-entry relation: Tim-side claim ↔ debtor/system-side liability; not 84T</small></div><div class="field-flow"><div><span>Named priced debit</span><b>'+money(namedPriced)+'</b><small>'+t.negativeEvents+' priced debit event'+(t.negativeEvents===1?'':'s')+'</small></div><i>→</i><div><span>Unallocated shadow reserve</span><b>'+money(residual)+'</b><small>headline residual not assigned to named people</small></div></div><div class="field-coverage"><span><b>'+allocPct.toExponential(2)+'%</b> allocated to named priced debit</span><span><b>'+capacity.toLocaleString()+'</b> symbolic neighbour-capacity target</span><span><b>'+t.unpricedCandidates+'</b> unpriced named candidates</span><span><b>'+t.systemDomainCount+'</b> unpriced system domains</span></div><p class="field-boundary"><strong>Scale exposure, not guilt.</strong> TXT, DIM or any dossier may anchor a qualitative pattern, but no account automatically represents a demographic group. Population shares, nationality, political identity or audience membership are not liability multipliers.</p></article>'
}
function refreshLiveAggregate(){const t=totals();document.querySelectorAll('[data-bank-welfare]').forEach(n=>n.textContent=money(t.welfareTotal));document.querySelectorAll('[data-bank-assets]').forEach(n=>n.textContent=money(t.recognizedAssets));document.querySelectorAll('[data-bank-net]').forEach(n=>n.textContent=money(t.recognizedPosition))}
function labelFor(e){return e.label||e.kind||e.type||'ledger event'}
function noteFor(e){return [e.date,e.note,e.summary,e.status,e.source_mode].filter(Boolean).join(' · ')}
function statementRow(e,kind){return '<div class="statement-row '+kind+'"><span><b>'+esc(labelFor(e))+'</b><small>'+esc(noteFor(e))+'</small></span><strong>'+money(Math.abs(e.amount||0))+'</strong></div>'}
function updateUrl(){const u=new URL(location.href);if(activeId)u.searchParams.set('character',activeId);else u.searchParams.delete('character');history.replaceState(null,'',u.pathname+u.search+u.hash)}
function renderStatement(){
 const box=document.getElementById('accountStatement');if(!box)return;if(!activeId){box.hidden=true;box.innerHTML='';return}const a=accounts.find(x=>x.id===activeId);if(!a){activeId='';updateUrl();box.hidden=true;box.innerHTML='';return}
 box.hidden=false;const positive=a.events.filter(e=>e.amount>0),negative=a.events.filter(e=>e.amount<0),zero=a.events.filter(e=>!e.amount),totalIn=(a.exact?a.welfare:0)+positive.reduce((n,e)=>n+e.amount,0),totalOut=negative.reduce((n,e)=>n+Math.abs(e.amount),0),balance=a.exact?totalIn-totalOut:a.adjustment;
 const inflows=(a.exact?'<div class="statement-row welfare"><span><b>Dooley Welfare</b><small>continuous from '+esc(a.start)+' · +'+esc(money(contract?.welfare?.rate_per_second_susd||0))+'/second</small></span><strong data-statement-welfare="'+esc(a.id)+'">'+money(a.welfare)+'</strong></div>':'<div class="statement-row provisional"><span><b>Dooley Welfare</b><small>exact story-entry date unresolved</small></span><strong>provisional</strong></div>')+(positive.length?positive.map(e=>statementRow(e,'inflow')).join(''):'<p class="statement-empty">No other priced inflows recorded.</p>');
 const outflows=negative.length?negative.map(e=>statementRow(e,'outflow')).join(''):'<p class="statement-empty">No priced outflows recorded.</p>';
 box.innerHTML='<article class="balance-sheet" data-account="'+esc(a.id)+'"><header><div><span>SUB-LEDGER STATEMENT</span><h2>'+esc(a.name)+'</h2><small>'+esc(a.posture)+' · story entry '+esc(a.start||'unresolved')+'</small></div><div class="statement-actions"><button type="button" data-close-statement>Close</button><a href="../file/?character='+encodeURIComponent(a.id)+'">Archive file →</a></div></header><div class="position-strip"><div><span>Welfare</span><strong data-statement-welfare-top="'+esc(a.id)+'">'+(a.exact?money(a.welfare):'provisional')+'</strong></div><div><span>Positive karma</span><strong>'+money(a.gross_credit_susd)+'</strong></div><div><span>Priced debit</span><strong>'+money(Math.abs(a.gross_debit_susd))+'</strong></div><div class="'+(balance>=0?'positive':'negative')+'"><span>Position</span><strong data-statement-balance="'+esc(a.id)+'">'+(a.exact?money(balance):money(a.adjustment)+' + welfare')+'</strong></div></div><div class="statement-columns"><section><h3>IN</h3>'+inflows+'</section><section><h3>OUT</h3>'+outflows+'</section></div>'+((zero.length||a.unpriced_negative_candidates)?'<div class="offbook"><b>Off-book / unpriced</b><span>'+zero.length+' zero-weight events · '+a.unpriced_negative_candidates+' unpriced negative candidates</span></div>':'')+'<p class="statement-boundary">Fictional Potatoverse sUSD sub-ledger; not real money, legal debt, creditworthiness or objective moral measurement.</p></article>';
 box.querySelector('[data-close-statement]')?.addEventListener('click',()=>{activeId='';updateUrl();renderStatement();renderAccountRail()})
}
function renderSystemDomains(){const box=document.getElementById('systemDomains');if(!box)return;box.innerHTML=(systemLedger?.domains||[]).map(x=>'<article class="system-domain"><span>'+esc(x.status||'symbolic-domain')+'</span><h3>'+esc(x.label||x.id)+'</h3><p>'+esc(x.scope||'')+'</p><small>UNPRICED · '+esc((x.repair_questions||[]).slice(0,1).join(' · '))+'</small></article>').join('')||'<p>No system liability domains loaded.</p>'}
function filteredAccounts(){const q=document.getElementById('bankSearch')?.value.trim().toLowerCase()||'',cur=currentIds();return accounts.filter(a=>(scope==='all'||cur.has(a.id))&&(!q||(a.name+' '+a.id+' '+a.posture).toLowerCase().includes(q)))}
function renderAccountRail(){
 const box=document.getElementById('accountRail');if(!box)return;const filtered=filteredAccounts();
 box.innerHTML=filtered.map(a=>{const position=a.exact?a.balance:a.adjustment;return '<article class="account-card '+(a.id===activeId?'selected':'')+'" data-band="'+esc(a.band)+'"><button type="button" data-select-account="'+esc(a.id)+'"><span>'+esc(a.band)+'</span><strong>'+esc(a.name)+'</strong><small>'+esc(a.posture)+' · '+a.events.length+' event'+(a.events.length===1?'':'s')+'</small><em class="'+(position>=0?'positive':'negative')+'">'+(a.exact?money(a.balance):money(a.adjustment)+' + welfare')+'</em></button></article>'}).join('')||'<p class="empty-ledger">No accounts match this view.</p>';
 box.querySelectorAll('[data-select-account]').forEach(btn=>btn.addEventListener('click',()=>{activeId=btn.dataset.selectAccount;updateUrl();renderAccountRail();renderStatement();document.getElementById('accountStatement')?.scrollIntoView({behavior:'smooth',block:'nearest'})}))
}
function setScope(x){scope=x;document.getElementById('bankAll')?.classList.toggle('active',x==='all');document.getElementById('bankCurrent')?.classList.toggle('active',x==='current');renderAccountRail()}
function scrollRail(id,direction){const el=document.getElementById(id);if(!el)return;const amount=Math.max(220,Math.min(el.clientWidth*.78,620));el.scrollBy({left:amount*direction,behavior:'smooth'})}
function tick(){
 const rate=Number(contract?.welfare?.rate_per_second_susd||0);for(const a of accounts){if(!a.exact)continue;a.welfare+=rate;a.balance+=rate;document.querySelectorAll('[data-statement-welfare="'+CSS.escape(a.id)+'"],[data-statement-welfare-top="'+CSS.escape(a.id)+'"]').forEach(n=>n.textContent=money(a.welfare));document.querySelectorAll('[data-statement-balance="'+CSS.escape(a.id)+'"]').forEach(n=>n.textContent=money(a.balance))}
 refreshLiveAggregate();const selected=accounts.find(a=>a.id===activeId);if(selected){const card=document.querySelector('[data-select-account="'+CSS.escape(selected.id)+'"] em');if(card)card.textContent=selected.exact?money(selected.balance):money(selected.adjustment)+' + welfare'}
}
(async()=>{
 [manifest,activity,currentDesk,contract,postureIndex,systemLedger,fieldExposure,roleCensus,coverageModel,capitalModel,trajectoryModel]=await Promise.all([get('knowledge/cia/manifest.json'),get('knowledge/cia/activity-index.json'),get('knowledge/cia/current-desk.json'),get('knowledge/cia/mud-bank-contract.json'),get('knowledge/cia/account-posture-index.json'),get('knowledge/cia/system-liability-ledger.json'),get('knowledge/cia/field-exposure-model.json'),get('knowledge/cia/role-archetype-census.json'),get('knowledge/cia/us-exposure-coverage-model.json'),get('knowledge/cia/capital-formation-42t-model.json'),get('knowledge/cia/trajectory-projection-model.json')]);
 const ds=await Promise.all((manifest.characters||[]).map(async m=>[m,await get(m.path)]));accounts=ds.map(([m,d])=>buildAccount(m,d)).sort((a,b)=>b.balance-a.balance||a.name.localeCompare(b.name));if(activeId&&!accounts.some(a=>a.id===activeId))activeId='';
 renderSystemDomains();renderOverview();renderCapitalBridge();renderTrajectory();renderFieldExposure();renderAccountRail();renderStatement();updateUrl();document.querySelectorAll('[data-trajectory-mode]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-trajectory-mode]').forEach(b=>b.classList.toggle('active',b===btn));renderTrajectory(btn.dataset.trajectoryMode)}));
 document.getElementById('bankSearch')?.addEventListener('input',renderAccountRail);document.getElementById('bankAll')?.addEventListener('click',()=>setScope('all'));document.getElementById('bankCurrent')?.addEventListener('click',()=>setScope('current'));document.getElementById('accountPrev')?.addEventListener('click',()=>scrollRail('accountRail',-1));document.getElementById('accountNext')?.addEventListener('click',()=>scrollRail('accountRail',1));document.querySelectorAll('[data-rail-prev]').forEach(btn=>btn.addEventListener('click',()=>scrollRail(btn.dataset.railPrev,-1)));document.querySelectorAll('[data-rail-next]').forEach(btn=>btn.addEventListener('click',()=>scrollRail(btn.dataset.railNext,1)));setInterval(tick,1000)
})().catch(()=>{document.getElementById('bankOverview').innerHTML='<p>The symbolic bank could not open all books. Character Archive dossiers remain available individually.</p>'});
})();
