#!/usr/bin/env python3
"""Audit the files that can actually participate in the GitHub Pages surface.

The scope intentionally mirrors ``scripts/build_site.py``. Historical/archive,
tooling and build-only trees are useful repository strata but are not deployed
public assets and therefore must not create false web-integrity failures.

Some public routes (notably ``questions/`` and ``index-a-z/``) are generated by
``scripts/build_discovery.py`` into ``_site`` rather than stored as source HTML.
The source-time audit recognizes those route roots; the later built-site validator
remains responsible for proving that generation actually happened.

The Pages workflow also vendors the MapLibre runtime under
``_site/world-map/vendor``. Source HTML/JS may legitimately reference that
build-generated subtree even though it does not exist in the repository checkout.

HTML documents may define ``<base href>``. Relative href/src values are resolved
against that browser base rather than blindly against the HTML file's directory.

The audit also writes ``audit-web-report.txt`` so CI failures remain inspectable
without weakening the gate.
"""
from __future__ import annotations

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "audit-web-report.txt"
errors: list[str] = []
warnings: list[str] = []

EXCLUDED_PARTS = {
    ".git",
    ".github",
    "_site",
    "node_modules",
    "vendor",
    "__pycache__",
    "components",
    "scripts",
    "archive",
}

# Route roots intentionally generated into _site by scripts/build_discovery.py.
GENERATED_PUBLIC_ROUTE_ROOTS = {
    "questions",
    "index-a-z",
}

# Public asset subtrees intentionally generated by the deployment workflow.
# Keep this narrow: allowing arbitrary missing folders would weaken the audit.
GENERATED_PUBLIC_PATH_PREFIXES = {
    ("world-map", "vendor"),
}


def is_public_source(path: Path) -> bool:
    rel = path.relative_to(ROOT)
    return not any(part in EXCLUDED_PARTS for part in rel.parts)


html_files = sorted(p for p in ROOT.rglob("*.html") if is_public_source(p))
css_files = sorted(p for p in ROOT.rglob("*.css") if is_public_source(p))
js_files = sorted(p for p in ROOT.rglob("*.js") if is_public_source(p))

attr_re = re.compile(r"\b(?:href|src)=[\"']([^\"']+)[\"']", re.I)
base_tag_re = re.compile(r"<base\b[^>]*\bhref=[\"']([^\"']+)[\"'][^>]*>", re.I)
css_url_re = re.compile(r"url\(\s*([\"']?)([^\"')]+)\1\s*\)", re.I)
js_import_re = re.compile(r"\bimport\s*\(\s*[\"']([^\"']+)[\"']\s*\)", re.I)
external = (
    "http://",
    "https://",
    "//",
    "mailto:",
    "tel:",
    "javascript:",
    "data:",
    "blob:",
)


def local(raw: str) -> str | None:
    raw = raw.split("#", 1)[0].split("?", 1)[0].strip()
    return None if not raw or raw.startswith(external) or raw.startswith(("${", "<", "`")) else raw


def repo_relative(path: Path) -> Path | None:
    try:
        return path.relative_to(ROOT.resolve())
    except ValueError:
        return None


def is_generated_public_target(path: Path) -> bool:
    """Return True when a missing source path is intentionally build-generated."""
    rel = repo_relative(path)
    if rel is None:
        return False
    if rel.parts and rel.parts[0] in GENERATED_PUBLIC_ROUTE_ROOTS:
        return True
    return any(rel.parts[: len(prefix)] == prefix for prefix in GENERATED_PUBLIC_PATH_PREFIXES)


def check(source: Path, raw: str, label: str, *, base_dir: Path | None = None) -> None:
    target = local(raw)
    if not target:
        return
    if target.startswith("/"):
        errors.append(f"{source.relative_to(ROOT)}: root-relative reference -> {raw}")
        return

    p = ((base_dir or source.parent) / target).resolve()
    if repo_relative(p) is None:
        warnings.append(f"{source.relative_to(ROOT)}: reference escapes repository -> {raw}")
        return

    if not p.exists() and not is_generated_public_target(p):
        errors.append(f"{source.relative_to(ROOT)}: broken {label} -> {target}")


def html_resolution_base(page: Path, text: str) -> tuple[Path, tuple[int, int] | None]:
    """Resolve a document's browser base and return the base-tag span to skip.

    The base href itself is resolved against the document URL. Other relative
    href/src references are then resolved against that base, matching browser
    behavior closely enough for repository-local Pages paths.
    """
    match = base_tag_re.search(text)
    if not match:
        return page.parent, None

    raw = match.group(1)
    target = local(raw)
    if not target:
        return page.parent, match.span()
    if target.startswith("/"):
        # Root-relative references are intentionally disallowed by this audit;
        # preserve the existing rule rather than silently translating one here.
        errors.append(f"{page.relative_to(ROOT)}: root-relative base reference -> {raw}")
        return page.parent, match.span()

    resolved = (page.parent / target).resolve()
    if repo_relative(resolved) is None:
        warnings.append(f"{page.relative_to(ROOT)}: base reference escapes repository -> {raw}")
        return page.parent, match.span()
    return resolved, match.span()


for page in html_files:
    text = page.read_text(encoding="utf-8", errors="replace")
    base_dir, base_span = html_resolution_base(page, text)
    if base_span:
        # Do not re-interpret the <base href> against itself. Browser semantics
        # resolve it against the document, which html_resolution_base handled.
        text = text[: base_span[0]] + text[base_span[1] :]
    for raw in attr_re.findall(text):
        check(page, raw, "HTML reference", base_dir=base_dir)

for css in css_files:
    text = css.read_text(encoding="utf-8", errors="replace")
    for _, raw in css_url_re.findall(text):
        check(css, raw, "CSS asset")

for js in js_files:
    text = js.read_text(encoding="utf-8", errors="replace")
    for raw in js_import_re.findall(text):
        check(js, raw, "JavaScript import")

if not (ROOT / "index.html").exists():
    errors.append("Missing index.html public Door")
if not (ROOT / "app" / "app.js").exists():
    errors.append("Missing app/app.js archive explorer entry point")
if not (ROOT / "app" / "style.css").exists():
    errors.append("Missing app/style.css primary site stylesheet")

lines = [
    "Public application root: /TimDooley/",
    f"HTML pages audited: {len(html_files)}",
    f"CSS files audited: {len(css_files)}",
    f"JS files audited: {len(js_files)}",
    f"Generated route roots recognized: {', '.join(sorted(GENERATED_PUBLIC_ROUTE_ROOTS))}",
    "Generated asset roots recognized: " + ", ".join("/".join(prefix) for prefix in sorted(GENERATED_PUBLIC_PATH_PREFIXES)),
    f"Errors: {len(errors)}",
    f"Warnings: {len(warnings)}",
]
lines.extend(f"ERROR: {item}" for item in errors)
lines.extend(f"WARNING: {item}" for item in warnings)
report = "\n".join(lines) + "\n"
REPORT.write_text(report, encoding="utf-8")
print(report, end="")

sys.exit(1 if errors else 0)